export interface BackendModelPreset {
  model_id: string;
  name: string;
  description: string;
  max_context: number;
  max_output: number;
  input_token_price: number;
  output_token_price: number;
  maker: string;
  provider: string;
  provider_model: string;
  provider_endpoint: string;
  max_image_attachments: number;
  max_tools: number;
  aa_score: number[];
  release_date: string[];
  status: { Active: null } | { Paused: null };
  extra_body_json?: string;
  is_reasoning?: boolean;
  is_embedding?: boolean;
  is_featured?: boolean;
}

export const MODEL_PRESETS: BackendModelPreset[] = [
  {
    model_id: "openrouter-sonar-pro-search",
    name: "Sonar Pro Search",
    description: "Sonar Pro Search model, provided via OpenRouter.",
    max_context: 200_000,
    max_output: 16_384,
    input_token_price: 3.0 / 1_000_000.0,
    output_token_price: 15.0 / 1_000_000.0,
    maker: "perplexity",
    provider: "openrouter",
    provider_model: "perplexity/sonar-pro-search",
    provider_endpoint: "https://openrouter.ai/api/v1",
    max_image_attachments: 0,
    max_tools: 0,
    aa_score: [28],
    release_date: ["2025"],
    status: { Active: null },
    extra_body_json: JSON.stringify({
      // return_images: false,
      // return_related_questions: false,
      web_search_options: {
        // search_type: "pro",
        search_context_size: "high",
        // search_recency_filter: "month",
        // search_domain_filter: ["wikipedia.org", "nytimes.com"],
      },
    }),
    is_reasoning: false,
    is_embedding: false,
    is_featured: false,
  },
  {
    model_id: "xai-grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast",
    description: "Grok 4.1 Fast model, provided via xAI.",
    max_context: 120_832,
    max_output: 10_240,
    input_token_price: 0.2 / 1_000_000.0,
    output_token_price: 0.5 / 1_000_000.0,
    maker: "xai",
    provider: "xai",
    provider_model: "grok-4-1-fast-non-reasoning",
    provider_endpoint: "https://api.x.ai/v1",
    max_image_attachments: 5,
    max_tools: 10,
    aa_score: [64],
    release_date: ["November 19, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "groq-gpt-oss-20b",
    name: "GPT OSS 20B",
    description: "GPT OSS 20B model, provided via Groq.",
    max_context: 131_072,
    max_output: 65_536,
    input_token_price: 0.075 / 1_000_000.0,
    output_token_price: 0.3 / 1_000_000.0,
    maker: "openai",
    provider: "groq",
    provider_model: "openai/gpt-oss-20b",
    provider_endpoint: "https://api.groq.com/openai/v1",
    max_image_attachments: 0,
    max_tools: 10,
    aa_score: [52],
    release_date: ["August 5, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "deepinfra-qwen3-vl-30b-a3b-instruct",
    name: "Qwen3 VL 30B",
    description: "Qwen3 VL 30B-A3B model, provided via DeepInfra.",
    max_context: 262_144,
    max_output: 131_072,
    input_token_price: 0.15 / 1_000_000.0,
    output_token_price: 0.6 / 1_000_000.0,
    maker: "qwen",
    provider: "deepinfra",
    provider_model: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    provider_endpoint: "https://api.deepinfra.com/v1/openai",
    max_image_attachments: 5,
    max_tools: 10,
    aa_score: [45],
    release_date: ["September 23, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "groq-qwen-3-32b",
    name: "Qwen 3 32B",
    description: "Qwen 3 32B model, provided via Groq.",
    max_context: 131_072,
    max_output: 8192,
    input_token_price: 0.29 / 1_000_000.0,
    output_token_price: 0.59 / 1_000_000.0,
    maker: "qwen",
    provider: "groq",
    provider_model: "qwen/qwen3-32b",
    provider_endpoint: "https://api.groq.com/openai/v1",
    max_image_attachments: 0,
    max_tools: 10,
    aa_score: [39],
    release_date: ["April 29, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "groq-llama-4-maverick",
    name: "Llama 4 Maverick",
    description: "Llama 4 Maverick model, provided via Groq.",
    max_context: 131_072,
    max_output: 8192,
    input_token_price: 0.2 / 1_000_000.0,
    output_token_price: 0.6 / 1_000_000.0,
    maker: "meta",
    provider: "groq",
    provider_model: "meta-llama/llama-4-maverick-17b-128e-instruct",
    provider_endpoint: "https://api.groq.com/openai/v1",
    max_image_attachments: 5,
    max_tools: 0,
    aa_score: [36],
    release_date: ["April 5, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "groq-llama-4-scout",
    name: "Llama 4 Scout",
    description: "Llama 4 Scout model, provided via Groq.",
    max_context: 131_072,
    max_output: 8192,
    input_token_price: 0.11 / 1_000_000.0,
    output_token_price: 0.34 / 1_000_000.0,
    maker: "meta",
    provider: "groq",
    provider_model: "meta-llama/llama-4-scout-17b-16e-instruct",
    provider_endpoint: "https://api.groq.com/openai/v1",
    max_image_attachments: 5,
    max_tools: 0,
    aa_score: [28],
    release_date: ["April 5, 2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: false,
    is_featured: true,
  },
  {
    model_id: "deepinfra-qwen3-embedding-8b",
    name: "Qwen3 Embedding 8B",
    description: "Qwen3 Embedding 8B model for text embeddings, provided via DeepInfra.",
    max_context: 32_768,
    max_output: 0,
    input_token_price: 0.05 / 1_000_000.0,
    output_token_price: 0.0,
    maker: "qwen",
    provider: "deepinfra",
    provider_model: "Qwen/Qwen3-Embedding-8B",
    provider_endpoint: "https://api.deepinfra.com/v1/openai",
    max_image_attachments: 0,
    max_tools: 0,
    aa_score: [],
    release_date: ["2025"],
    status: { Active: null },
    is_reasoning: false,
    is_embedding: true,
    is_featured: false,
  },
];
