/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Tool = IDL.Record({
    'name' : IDL.Text,
    'parameters' : IDL.Text,
    'description' : IDL.Text,
  });
  const Role = IDL.Variant({
    'System' : IDL.Null,
    'Tool' : IDL.Null,
    'User' : IDL.Null,
    'Assistant' : IDL.Null,
  });
  const ImageAttachment = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'mime_type' : IDL.Text,
  });
  const AddMessageRequest = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'content' : IDL.Vec(IDL.Nat8),
    'temperature' : IDL.Float32,
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'role' : Role,
    'parent_message_id' : IDL.Opt(IDL.Nat64),
    'max_completion_tokens' : IDL.Nat32,
    'reasoning_effort' : IDL.Opt(IDL.Text),
    'model_id' : IDL.Text,
    'chat_id' : IDL.Nat64,
    'attachments' : IDL.Opt(IDL.Vec(ImageAttachment)),
    'max_context' : IDL.Nat32,
  });
  const GenerationStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Job = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'updated_at' : IDL.Nat64,
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'temperature' : IDL.Float32,
    'extra_body_json' : IDL.Opt(IDL.Text),
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Nat64,
    'max_completion_tokens' : IDL.Nat32,
    'job_id' : IDL.Nat64,
    'placeholder_message_id' : IDL.Nat64,
    'reasoning_effort' : IDL.Opt(IDL.Text),
    'model_id' : IDL.Text,
    'chat_id' : IDL.Nat64,
    'generation_status' : GenerationStatus,
    'max_context' : IDL.Nat32,
  });
  const FunctionCall = IDL.Record({
    'name' : IDL.Text,
    'arguments' : IDL.Text,
  });
  const ToolCall = IDL.Record({
    'id' : IDL.Text,
    'function' : FunctionCall,
    'type' : IDL.Text,
  });
  const ProviderErrorType = IDL.Variant({
    'InvalidImage' : IDL.Text,
    'NetworkError' : IDL.Null,
    'ContentPolicyViolation' : IDL.Null,
    'ContextLengthExceeded' : IDL.Null,
    'ServiceUnavailable' : IDL.Null,
    'RateLimited' : IDL.Null,
    'Timeout' : IDL.Null,
    'Unknown' : IDL.Text,
    'AuthenticationError' : IDL.Null,
    'BadRequest' : IDL.Null,
    'ServerError' : IDL.Null,
  });
  const MessageErrorStatus = IDL.Variant({
    'NodeOffline' : IDL.Null,
    'ProviderError' : ProviderErrorType,
    'Timeout' : IDL.Null,
    'Unknown' : IDL.Text,
    'ConfigurationError' : IDL.Text,
    'CanisterCallError' : IDL.Text,
    'InvalidState' : IDL.Text,
  });
  const TokenUsage = IDL.Record({
    'completion_tokens' : IDL.Nat32,
    'prompt_tokens' : IDL.Nat32,
    'total_tokens' : IDL.Nat32,
  });
  const ToolResult = IDL.Record({
    'content' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'tool_call_id' : IDL.Text,
  });
  const Message = IDL.Record({
    'updated_at' : IDL.Nat64,
    'content' : IDL.Vec(IDL.Nat8),
    'tool_calls' : IDL.Opt(IDL.Vec(ToolCall)),
    'role' : Role,
    'parent_message_id' : IDL.Opt(IDL.Nat64),
    'error_status' : IDL.Opt(MessageErrorStatus),
    'created_at' : IDL.Nat64,
    'tool_call_id' : IDL.Opt(IDL.Text),
    'requires_client_action' : IDL.Bool,
    'usage' : IDL.Opt(TokenUsage),
    'tool_results' : IDL.Opt(IDL.Vec(ToolResult)),
    'chat_id' : IDL.Nat64,
    'message_id' : IDL.Nat64,
    'attachments' : IDL.Opt(IDL.Vec(ImageAttachment)),
  });
  const AddMessageResponse = IDL.Record({
    'job' : Job,
    'ai_message' : Message,
    'message' : Message,
  });
  const CanisterError = IDL.Variant({
    'CannotDeleteRootFolder' : IDL.Null,
    'UserAlreadyRegistered' : IDL.Null,
    'InvalidFileName' : IDL.Text,
    'DeleteNonEmptyFolder' : IDL.Null,
    'ModelNotFound' : IDL.Null,
    'InvalidPathDepth' : IDL.Null,
    'InvalidInput' : IDL.Text,
    'UnsupportedMimeType' : IDL.Text,
    'PoolExhausted' : IDL.Null,
    'NoAvailableUserCanister' : IDL.Null,
    'MessageNotFound' : IDL.Null,
    'FileSystemLimitExceeded' : IDL.Text,
    'ChatNotFound' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'FileNotFound' : IDL.Null,
    'CallError' : IDL.Text,
    'PathNotFound' : IDL.Null,
    'ItemNameCollision' : IDL.Text,
    'GenerationInProgress' : IDL.Null,
    'NodeNotFound' : IDL.Null,
    'InvalidSecretKey' : IDL.Null,
    'FolderNotFound' : IDL.Null,
    'Other' : IDL.Text,
    'TrialExpired' : IDL.Null,
    'RoleAlreadyClaimed' : IDL.Null,
    'UserNotFound' : IDL.Null,
  });
  const Result = IDL.Variant({
    'Ok' : AddMessageResponse,
    'Err' : CanisterError,
  });
  const ArchiveChatRequest = IDL.Record({ 'chat_id' : IDL.Nat64 });
  const Chat = IDL.Record({
    'title' : IDL.Text,
    'updated_at' : IDL.Nat64,
    'owner' : IDL.Principal,
    'job_ids' : IDL.Vec(IDL.Nat64),
    'created_at' : IDL.Nat64,
    'message_ids' : IDL.Vec(IDL.Nat64),
    'encryption_salt' : IDL.Vec(IDL.Nat8),
    'chat_id' : IDL.Nat64,
    'temporary' : IDL.Bool,
    'active_job_id' : IDL.Opt(IDL.Nat64),
    'archived' : IDL.Bool,
  });
  const ArchiveChatResponse = IDL.Record({ 'chat' : Chat });
  const Result_1 = IDL.Variant({
    'Ok' : ArchiveChatResponse,
    'Err' : CanisterError,
  });
  const ClaimJobRequest = IDL.Record({ 'job_id' : IDL.Nat64 });
  const ClaimJobResponse = IDL.Record({
    'job' : Job,
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'chat' : Chat,
    'message_chain_ids' : IDL.Vec(IDL.Nat64),
  });
  const Result_2 = IDL.Variant({
    'Ok' : ClaimJobResponse,
    'Err' : CanisterError,
  });
  const JobCompletionResult = IDL.Variant({
    'Success' : IDL.Vec(IDL.Nat8),
    'ToolCall' : IDL.Vec(ToolCall),
    'Failure' : MessageErrorStatus,
  });
  const CompleteJobRequest = IDL.Record({
    'result' : JobCompletionResult,
    'job_id' : IDL.Nat64,
    'usage' : IDL.Opt(TokenUsage),
  });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : CanisterError });
  const ToolResponseMessage = IDL.Record({
    'content' : IDL.Text,
    'tool_call_id' : IDL.Text,
  });
  const ContinueFromToolResponseRequest = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'responses' : IDL.Vec(ToolResponseMessage),
    'assistant_message_id' : IDL.Nat64,
    'temperature' : IDL.Float32,
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'max_completion_tokens' : IDL.Nat32,
    'reasoning_effort' : IDL.Opt(IDL.Text),
    'model_id' : IDL.Text,
    'chat_id' : IDL.Nat64,
    'max_context' : IDL.Nat32,
  });
  const ContinueFromToolResponseResponse = IDL.Record({
    'new_ai_message_id' : IDL.Nat64,
    'job_id' : IDL.Nat64,
  });
  const Result_4 = IDL.Variant({
    'Ok' : ContinueFromToolResponseResponse,
    'Err' : CanisterError,
  });
  const CreateChatRequest = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'temperature' : IDL.Float32,
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'max_completion_tokens' : IDL.Nat32,
    'initial_message' : IDL.Vec(IDL.Nat8),
    'encryption_salt' : IDL.Vec(IDL.Nat8),
    'model_id' : IDL.Text,
    'temporary' : IDL.Bool,
    'attachments' : IDL.Opt(IDL.Vec(ImageAttachment)),
    'max_context' : IDL.Nat32,
  });
  const CreateChatResponse = IDL.Record({
    'ai_message_id' : IDL.Nat64,
    'job_id' : IDL.Nat64,
    'chat_id' : IDL.Nat64,
    'user_message_id' : IDL.Nat64,
  });
  const Result_5 = IDL.Variant({
    'Ok' : CreateChatResponse,
    'Err' : CanisterError,
  });
  const CreateFolderRequest = IDL.Record({
    'name' : IDL.Text,
    'parent_folder_id' : IDL.Nat64,
  });
  const FolderInfo = IDL.Record({
    'id' : IDL.Nat64,
    'updated_at' : IDL.Nat64,
    'name' : IDL.Text,
    'created_at' : IDL.Nat64,
  });
  const CreateFolderResponse = IDL.Record({ 'folder' : FolderInfo });
  const Result_6 = IDL.Variant({
    'Ok' : CreateFolderResponse,
    'Err' : CanisterError,
  });
  const DeleteChatRequest = IDL.Record({ 'chat_id' : IDL.Nat64 });
  const FsItemType = IDL.Variant({ 'Folder' : IDL.Null, 'File' : IDL.Null });
  const DeleteItemRequest = IDL.Record({
    'item_type' : FsItemType,
    'item_id' : IDL.Nat64,
  });
  const Result_7 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : CanisterError });
  const EditUserMessageRequest = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'old_user_message_id' : IDL.Nat64,
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'temperature' : IDL.Float32,
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'max_completion_tokens' : IDL.Nat32,
    'new_content' : IDL.Vec(IDL.Nat8),
    'reasoning_effort' : IDL.Opt(IDL.Text),
    'model_id' : IDL.Text,
    'chat_id' : IDL.Nat64,
    'attachments' : IDL.Opt(IDL.Vec(ImageAttachment)),
    'max_context' : IDL.Nat32,
  });
  const EditUserMessageResponse = IDL.Record({
    'job' : Job,
    'new_user_message' : Message,
    'new_ai_message' : Message,
  });
  const Result_8 = IDL.Variant({
    'Ok' : EditUserMessageResponse,
    'Err' : CanisterError,
  });
  const FinalizeRegistrationRequest = IDL.Record({
    'enc_salt' : IDL.Vec(IDL.Nat8),
    'enc_validator' : IDL.Text,
  });
  const FinalizeRegistrationResponse = IDL.Record({ 'success' : IDL.Bool });
  const Result_9 = IDL.Variant({
    'Ok' : FinalizeRegistrationResponse,
    'Err' : CanisterError,
  });
  const GetChatRequest = IDL.Record({ 'chat_id' : IDL.Nat64 });
  const GetChatResponse = IDL.Record({ 'chat' : Chat });
  const Result_10 = IDL.Variant({
    'Ok' : GetChatResponse,
    'Err' : CanisterError,
  });
  const GetChatJobsResponse = IDL.Record({ 'jobs' : IDL.Vec(Job) });
  const Result_11 = IDL.Variant({
    'Ok' : GetChatJobsResponse,
    'Err' : CanisterError,
  });
  const GetFileContentRequest = IDL.Record({ 'file_id' : IDL.Nat64 });
  const GetFileContentResponse = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'mime_type' : IDL.Text,
  });
  const Result_12 = IDL.Variant({
    'Ok' : GetFileContentResponse,
    'Err' : CanisterError,
  });
  const GetFolderContentRequest = IDL.Record({
    'folder_id' : IDL.Opt(IDL.Nat64),
  });
  const TextChunk = IDL.Record({
    'chunk_index' : IDL.Nat32,
    'end_char' : IDL.Nat32,
    'start_char' : IDL.Nat32,
    'embedding' : IDL.Vec(IDL.Nat8),
  });
  const FileInfo = IDL.Record({
    'id' : IDL.Nat64,
    'updated_at' : IDL.Nat64,
    'name' : IDL.Text,
    'mime_type' : IDL.Text,
    'created_at' : IDL.Nat64,
    'parent_folder_id' : IDL.Nat64,
    'content_size_bytes' : IDL.Nat64,
    'chunks' : IDL.Vec(TextChunk),
  });
  const GetFolderContentResponse = IDL.Record({
    'files' : IDL.Vec(FileInfo),
    'folder_name' : IDL.Text,
    'folders' : IDL.Vec(FolderInfo),
    'parent_folder_id' : IDL.Opt(IDL.Nat64),
    'folder_id' : IDL.Nat64,
  });
  const Result_13 = IDL.Variant({
    'Ok' : GetFolderContentResponse,
    'Err' : CanisterError,
  });
  const GetItemByPathRequest = IDL.Record({ 'path' : IDL.Text });
  const FsItemInfo = IDL.Variant({ 'Folder' : FolderInfo, 'File' : FileInfo });
  const GetItemByPathResponse = IDL.Record({ 'item' : FsItemInfo });
  const Result_14 = IDL.Variant({
    'Ok' : GetItemByPathResponse,
    'Err' : CanisterError,
  });
  const GetMessageRequest = IDL.Record({ 'message_id' : IDL.Nat64 });
  const GetMessageResponse = IDL.Record({ 'message' : Message });
  const Result_15 = IDL.Variant({
    'Ok' : GetMessageResponse,
    'Err' : CanisterError,
  });
  const LocalNode = IDL.Record({
    'node_id' : IDL.Nat64,
    'public_key' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'model_id' : IDL.Text,
    'node_principal' : IDL.Opt(IDL.Principal),
  });
  const GptUserGetNodesResponse = IDL.Record({ 'nodes' : IDL.Vec(LocalNode) });
  const Result_16 = IDL.Variant({
    'Ok' : GptUserGetNodesResponse,
    'Err' : CanisterError,
  });
  const GetUserStorageUsageResponse = IDL.Record({
    'limit_bytes' : IDL.Nat64,
    'usage_bytes' : IDL.Nat64,
  });
  const Result_17 = IDL.Variant({
    'Ok' : GetUserStorageUsageResponse,
    'Err' : CanisterError,
  });
  const IsUserFinalizedRequest = IDL.Record({
    'user_principal' : IDL.Principal,
  });
  const IsUserFinalizedResponse = IDL.Record({ 'is_finalized' : IDL.Bool });
  const ListChatsRequest = IDL.Record({ 'include_archived' : IDL.Bool });
  const ListChatsResponse = IDL.Record({ 'chats' : IDL.Vec(Chat) });
  const Result_18 = IDL.Variant({
    'Ok' : ListChatsResponse,
    'Err' : CanisterError,
  });
  const UserDetails = IDL.Record({
    'enc_salt' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'principal' : IDL.Principal,
    'enc_validator' : IDL.Opt(IDL.Text),
    'registered_at' : IDL.Nat64,
  });
  const GptUserListRegisteredUsersResponse = IDL.Record({
    'users' : IDL.Vec(UserDetails),
  });
  const Result_19 = IDL.Variant({
    'Ok' : GptUserListRegisteredUsersResponse,
    'Err' : CanisterError,
  });
  const NodeGetMessageRequest = IDL.Record({ 'message_id' : IDL.Nat64 });
  const NodeGetMessageResponse = IDL.Record({ 'message' : Message });
  const Result_20 = IDL.Variant({
    'Ok' : NodeGetMessageResponse,
    'Err' : CanisterError,
  });
  const RenameChatRequest = IDL.Record({
    'new_title' : IDL.Text,
    'chat_id' : IDL.Nat64,
  });
  const RenameItemRequest = IDL.Record({
    'item_type' : FsItemType,
    'new_name' : IDL.Text,
    'item_id' : IDL.Nat64,
  });
  const RenameItemResponse = IDL.Record({ 'item' : FsItemInfo });
  const Result_21 = IDL.Variant({
    'Ok' : RenameItemResponse,
    'Err' : CanisterError,
  });
  const RetryAiMessageRequest = IDL.Record({
    'custom_prompt' : IDL.Opt(IDL.Text),
    'tools' : IDL.Opt(IDL.Vec(Tool)),
    'node_id' : IDL.Nat64,
    'temperature' : IDL.Float32,
    'encrypted_chat_key' : IDL.Opt(IDL.Text),
    'max_completion_tokens' : IDL.Nat32,
    'reasoning_effort' : IDL.Opt(IDL.Text),
    'model_id' : IDL.Text,
    'chat_id' : IDL.Nat64,
    'max_context' : IDL.Nat32,
    'user_message_id' : IDL.Nat64,
  });
  const RetryAiMessageResponse = IDL.Record({
    'job' : Job,
    'new_ai_message' : Message,
  });
  const Result_22 = IDL.Variant({
    'Ok' : RetryAiMessageResponse,
    'Err' : CanisterError,
  });
  const StoreToolResultsRequest = IDL.Record({
    'assistant_message_id' : IDL.Nat64,
    'results' : IDL.Vec(ToolResult),
    'chat_id' : IDL.Nat64,
  });
  const UpdateMessageAttachmentsRequest = IDL.Record({
    'message_id' : IDL.Nat64,
    'attachments' : IDL.Opt(IDL.Vec(ImageAttachment)),
  });
  const UploadFileRequest = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'mime_type' : IDL.Text,
    'parent_folder_id' : IDL.Nat64,
    'chunks' : IDL.Opt(IDL.Vec(TextChunk)),
  });
  const UploadFileResponse = IDL.Record({ 'file' : FileInfo });
  const Result_23 = IDL.Variant({
    'Ok' : UploadFileResponse,
    'Err' : CanisterError,
  });
  const WhoAmIUserResponse = IDL.Record({
    'enc_salt' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'principal' : IDL.Principal,
    'enc_validator' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'add_message' : IDL.Func([AddMessageRequest], [Result], []),
    'archive_chat' : IDL.Func([ArchiveChatRequest], [Result_1], []),
    'claim_job' : IDL.Func([ClaimJobRequest], [Result_2], []),
    'complete_job' : IDL.Func([CompleteJobRequest], [Result_3], []),
    'continue_from_tool_response' : IDL.Func(
        [ContinueFromToolResponseRequest],
        [Result_4],
        [],
      ),
    'create_chat' : IDL.Func([CreateChatRequest], [Result_5], []),
    'create_folder' : IDL.Func([CreateFolderRequest], [Result_6], []),
    'delete_chat' : IDL.Func([DeleteChatRequest], [Result_3], []),
    'delete_item' : IDL.Func([DeleteItemRequest], [Result_7], []),
    'edit_user_message' : IDL.Func([EditUserMessageRequest], [Result_8], []),
    'finalize_registration' : IDL.Func(
        [FinalizeRegistrationRequest],
        [Result_9],
        [],
      ),
    'get_chat' : IDL.Func([GetChatRequest], [Result_10], ['query']),
    'get_chat_jobs' : IDL.Func([GetChatRequest], [Result_11], ['query']),
    'get_file_content' : IDL.Func(
        [GetFileContentRequest],
        [Result_12],
        ['query'],
      ),
    'get_folder_content' : IDL.Func(
        [GetFolderContentRequest],
        [Result_13],
        ['query'],
      ),
    'get_item_by_path' : IDL.Func(
        [GetItemByPathRequest],
        [Result_14],
        ['query'],
      ),
    'get_message' : IDL.Func([GetMessageRequest], [Result_15], ['query']),
    'get_nodes' : IDL.Func([], [Result_16], ['query']),
    'get_user_storage_usage' : IDL.Func([], [Result_17], ['query']),
    'is_user_finalized' : IDL.Func(
        [IsUserFinalizedRequest],
        [IsUserFinalizedResponse],
        ['query'],
      ),
    'list_chats' : IDL.Func([ListChatsRequest], [Result_18], ['query']),
    'list_registered_users' : IDL.Func([], [Result_19], ['query']),
    'node_get_message' : IDL.Func(
        [NodeGetMessageRequest],
        [Result_20],
        ['query'],
      ),
    'rename_chat' : IDL.Func([RenameChatRequest], [Result_10], []),
    'rename_item' : IDL.Func([RenameItemRequest], [Result_21], []),
    'retry_ai_message' : IDL.Func([RetryAiMessageRequest], [Result_22], []),
    'store_tool_results' : IDL.Func([StoreToolResultsRequest], [Result_7], []),
    'unarchive_chat' : IDL.Func([GetChatRequest], [Result_10], []),
    'update_message_attachments' : IDL.Func(
        [UpdateMessageAttachmentsRequest],
        [Result_7],
        [],
      ),
    'upload_file' : IDL.Func([UploadFileRequest], [Result_23], []),
    'whoami' : IDL.Func([], [WhoAmIUserResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return [IDL.Principal]; };