/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddManagerRequest { 'principal_to_add' : Principal }
export interface AddMeasurementRequest {
  'name' : string,
  'measurement_hex' : string,
}
export interface AddModelRequest { 'model' : Model }
export interface AttestationMeasurement {
  'status' : MeasurementStatus,
  'updated_at' : bigint,
  'name' : string,
  'created_at' : bigint,
  'measurement_hex' : string,
}
export interface AttestationRequirements {
  'max_attestation_age_ns' : bigint,
  'min_report_version' : number,
  'require_ciphertext_hiding_enabled' : boolean,
  'require_tsme_disabled' : boolean,
  'genoa_policy' : GenTcbRequirements,
  'expected_measurement_len' : bigint,
  'measurements' : Array<AttestationMeasurement>,
  'require_ecc_enabled' : boolean,
  'require_smt_disabled' : boolean,
  'turin_policy' : GenTcbRequirements,
  'require_rapl_disabled' : boolean,
  'milan_policy' : GenTcbRequirements,
}
export type CanisterError = { 'CannotDeleteRootFolder' : null } |
  { 'UserAlreadyRegistered' : null } |
  { 'InvalidFileName' : string } |
  { 'DeleteNonEmptyFolder' : null } |
  { 'ModelNotFound' : null } |
  { 'InvalidPathDepth' : null } |
  { 'InvalidInput' : string } |
  { 'UnsupportedMimeType' : string } |
  { 'PoolExhausted' : null } |
  { 'NoAvailableUserCanister' : null } |
  { 'MessageNotFound' : null } |
  { 'FileSystemLimitExceeded' : string } |
  { 'ChatNotFound' : null } |
  { 'Unauthorized' : null } |
  { 'FileNotFound' : null } |
  { 'CallError' : string } |
  { 'PathNotFound' : null } |
  { 'ItemNameCollision' : string } |
  { 'GenerationInProgress' : null } |
  { 'NodeNotFound' : null } |
  { 'InvalidSecretKey' : null } |
  { 'FolderNotFound' : null } |
  { 'Other' : string } |
  { 'TrialExpired' : null } |
  { 'RoleAlreadyClaimed' : null } |
  { 'UserNotFound' : null };
export interface CanisterPoolEntry {
  'time_created' : bigint,
  'canister_id' : Principal,
  'state' : CanisterPoolState,
}
export type CanisterPoolState = { 'Available' : null } |
  { 'Assigned' : { 'owner' : Principal, 'expires_at' : [] | [bigint] } };
export interface ConfirmRegistrationRequest { 'user_principal' : Principal }
export interface CreateIndexNodeRequest {
  'hostname' : string,
  'encrypted_api_key' : string,
  'model_id' : string,
  'expected_chip_id' : string,
}
export interface CreateIndexNodeResponse { 'node_id' : bigint }
export interface CreateUserCanisterResponse { 'canister_id' : Principal }
export interface GenTcbRequirements {
  'min_tcb' : TcbVersion,
  'min_guest_svn' : number,
}
export interface GetAttestationRequirementsResponse {
  'requirements' : AttestationRequirements,
}
export interface GetModelsResponse { 'models' : Array<Model> }
export interface GetNodeConfigRequest { 'node_id' : bigint }
export interface GetNodeConfigResponse {
  'hostname' : string,
  'encrypted_api_key' : string,
  'model_id' : string,
}
export interface GetProvisioningInfoResponse {
  'owner' : Principal,
  'hostname' : string,
  'is_active' : boolean,
  'model_id' : string,
}
export interface GetUserAssignmentRequest { 'user_principal' : Principal }
export interface GetUserAssignmentResponse {
  'assigned_canister' : Array<Principal>,
}
export interface HeartbeatResponse { 'command' : NodeHeartbeatCommand }
export interface IsManagerResponse { 'is_manager' : boolean }
export interface ListActiveNodesResponse { 'nodes' : Array<PublicNodeInfo> }
export interface ListCanisterPoolResponse {
  'assigned' : Array<CanisterPoolEntry>,
  'available' : Array<CanisterPoolEntry>,
  'pool_target_size' : number,
}
export interface ListManagersResponse { 'managers' : Array<Principal> }
export interface ListMyNodesResponse { 'nodes' : Array<PublicNodeInfo> }
export interface ListUserCanistersResponse {
  'canisters' : Array<CanisterPoolEntry>,
}
export type MeasurementStatus = { 'Active' : null } |
  { 'Deprecated' : null } |
  { 'Revoked' : null };
export interface Model {
  'maker' : string,
  'status' : ModelStatus,
  'max_tools' : number,
  'max_output' : number,
  'provider' : string,
  'release_date' : [] | [string],
  'extra_body_json' : [] | [string],
  'max_image_attachments' : number,
  'name' : string,
  'description' : string,
  'output_token_price' : number,
  'provider_model' : string,
  'provider_endpoint' : string,
  'input_token_price' : number,
  'is_reasoning' : boolean,
  'model_id' : string,
  'aa_score' : [] | [number],
  'max_context' : number,
}
export type ModelStatus = { 'Paused' : null } |
  { 'Active' : null };
export type NodeHeartbeatCommand = { 'Continue' : null } |
  { 'Abort' : null } |
  { 'DrainAndShutdown' : null };
export interface ProvisionCanistersRequest { 'count' : number }
export interface ProvisionCanistersResponse {
  'pool_size' : number,
  'canisters_created' : number,
}
export interface PublicNodeInfo {
  'node_id' : bigint,
  'public_key' : [] | [string],
  'owner' : Principal,
  'detected_generation' : [] | [string],
  'hostname' : string,
  'attestation_verified_at' : [] | [bigint],
  'reported_measurement_hex' : [] | [string],
  'is_active' : boolean,
  'model_id' : string,
  'reported_chip_id_hex' : [] | [string],
  'node_principal' : [] | [Principal],
  'last_heartbeat_timestamp' : [] | [bigint],
}
export interface RawWhoAmIResponse { 'principal' : Principal }
export interface RegisterNodeRequest {
  'attestation_report' : Uint8Array,
  'node_id' : bigint,
  'ark_der' : Uint8Array,
  'public_key' : string,
  'vek_der' : Uint8Array,
  'ask_der' : Uint8Array,
  'timestamp' : bigint,
}
export interface RegisterNodeResponse { 'success' : boolean }
export interface RegisterUserRequest { 'username' : string }
export interface RegisterUserResponse {
  'principal' : Principal,
  'username' : string,
  'user_id' : bigint,
  'user_canister_id' : Principal,
}
export interface RemoveManagerRequest { 'principal_to_remove' : Principal }
export interface RemoveMeasurementRequest { 'measurement_hex' : string }
export type Result = { 'Ok' : null } |
  { 'Err' : CanisterError };
export type Result_1 = { 'Ok' : null } |
  { 'Err' : CanisterError };
export type Result_10 = { 'Ok' : ListActiveNodesResponse } |
  { 'Err' : CanisterError };
export type Result_11 = { 'Ok' : ListCanisterPoolResponse } |
  { 'Err' : CanisterError };
export type Result_12 = { 'Ok' : ListManagersResponse } |
  { 'Err' : CanisterError };
export type Result_13 = { 'Ok' : ListMyNodesResponse } |
  { 'Err' : CanisterError };
export type Result_14 = { 'Ok' : ListUserCanistersResponse } |
  { 'Err' : CanisterError };
export type Result_15 = { 'Ok' : ProvisionCanistersResponse } |
  { 'Err' : CanisterError };
export type Result_16 = { 'Ok' : RegisterNodeResponse } |
  { 'Err' : CanisterError };
export type Result_17 = { 'Ok' : RegisterUserResponse } |
  { 'Err' : CanisterError };
export type Result_2 = { 'Ok' : CreateIndexNodeResponse } |
  { 'Err' : CanisterError };
export type Result_3 = { 'Ok' : CreateUserCanisterResponse } |
  { 'Err' : CanisterError };
export type Result_4 = { 'Ok' : GetAttestationRequirementsResponse } |
  { 'Err' : CanisterError };
export type Result_5 = { 'Ok' : GetNodeConfigResponse } |
  { 'Err' : CanisterError };
export type Result_6 = { 'Ok' : GetProvisioningInfoResponse } |
  { 'Err' : CanisterError };
export type Result_7 = { 'Ok' : GetUserAssignmentResponse } |
  { 'Err' : CanisterError };
export type Result_8 = { 'Ok' : HeartbeatResponse } |
  { 'Err' : CanisterError };
export type Result_9 = { 'Ok' : IsManagerResponse } |
  { 'Err' : CanisterError };
export interface TcbVersion {
  'fmc' : number,
  'snp' : number,
  'tee' : number,
  'bootloader' : number,
  'microcode' : number,
}
export interface UpdateAttestationPoliciesRequest {
  'max_attestation_age_ns' : bigint,
  'min_report_version' : number,
  'require_ciphertext_hiding_enabled' : boolean,
  'require_tsme_disabled' : boolean,
  'genoa_policy' : GenTcbRequirements,
  'expected_measurement_len' : bigint,
  'require_ecc_enabled' : boolean,
  'require_smt_disabled' : boolean,
  'turin_policy' : GenTcbRequirements,
  'require_rapl_disabled' : boolean,
  'milan_policy' : GenTcbRequirements,
}
export interface UpdateMeasurementStatusRequest {
  'status' : MeasurementStatus,
  'measurement_hex' : string,
}
export interface WhoAmIResponse { 'principal' : Principal, 'username' : string }
export interface _SERVICE {
  'add_manager' : ActorMethod<[AddManagerRequest], Result>,
  'add_measurement' : ActorMethod<[AddMeasurementRequest], Result>,
  'add_model' : ActorMethod<[AddModelRequest], Result_1>,
  'claim_manager_role' : ActorMethod<[], Result_1>,
  'confirm_registration' : ActorMethod<[ConfirmRegistrationRequest], Result_1>,
  'create_node' : ActorMethod<[CreateIndexNodeRequest], Result_2>,
  /**
   * Creates a new user canister and adds it to the pool (manager-only or self-call).
   * This is the legacy endpoint - for pool management, use provision_canisters.
   */
  'create_user_canister' : ActorMethod<[], Result_3>,
  'get_attestation_requirements' : ActorMethod<[null], Result_4>,
  'get_models' : ActorMethod<[null], GetModelsResponse>,
  'get_node_config' : ActorMethod<[GetNodeConfigRequest], Result_5>,
  'get_provisioning_info' : ActorMethod<[GetNodeConfigRequest], Result_6>,
  'get_user_assignment' : ActorMethod<[GetUserAssignmentRequest], Result_7>,
  'heartbeat' : ActorMethod<[null], Result_8>,
  'is_manager' : ActorMethod<[], Result_9>,
  'list_active_nodes' : ActorMethod<[null], Result_10>,
  /**
   * Lists canister pool status with separation between available and assigned.
   */
  'list_canister_pool' : ActorMethod<[], Result_11>,
  'list_managers' : ActorMethod<[], Result_12>,
  'list_my_nodes' : ActorMethod<[null], Result_13>,
  /**
   * Lists all canisters in the pool (available and assigned).
   */
  'list_user_canisters' : ActorMethod<[], Result_14>,
  /**
   * Provisions additional canisters into the pool (manager-only).
   */
  'provision_canisters' : ActorMethod<[ProvisionCanistersRequest], Result_15>,
  'raw_whoami' : ActorMethod<[null], RawWhoAmIResponse>,
  'register_node' : ActorMethod<[RegisterNodeRequest], Result_16>,
  /**
   * Registers a new user by assigning them a canister from the pool.
   * - Managers get permanent canisters (no expiry)
   * - All other users get trial canisters that expire after 1 hour
   */
  'register_user' : ActorMethod<[RegisterUserRequest], Result_17>,
  'remove_manager' : ActorMethod<[RemoveManagerRequest], Result_1>,
  'remove_measurement' : ActorMethod<[RemoveMeasurementRequest], Result_1>,
  'unregister_node' : ActorMethod<[null], Result_1>,
  'update_attestation_policies' : ActorMethod<
    [UpdateAttestationPoliciesRequest],
    Result_1
  >,
  'update_measurement_status' : ActorMethod<
    [UpdateMeasurementStatusRequest],
    Result_1
  >,
  'update_model' : ActorMethod<[AddModelRequest], Result_1>,
  'whoami' : ActorMethod<[null], WhoAmIResponse>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];