/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const AddManagerRequest = IDL.Record({ 'principal_to_add' : IDL.Principal });
  const CanisterError = IDL.Variant({
    'CannotDeleteRootFolder' : IDL.Null,
    'UserAlreadyRegistered' : IDL.Null,
    'InvalidFileName' : IDL.Text,
    'DeleteNonEmptyFolder' : IDL.Null,
    'ModelNotFound' : IDL.Null,
    'InvalidPathDepth' : IDL.Null,
    'InvalidInput' : IDL.Text,
    'UnsupportedMimeType' : IDL.Text,
    'PoolExhausted' : IDL.Null,
    'NoAvailableUserCanister' : IDL.Null,
    'MessageNotFound' : IDL.Null,
    'FileSystemLimitExceeded' : IDL.Text,
    'ChatNotFound' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'FileNotFound' : IDL.Null,
    'CallError' : IDL.Text,
    'PathNotFound' : IDL.Null,
    'ItemNameCollision' : IDL.Text,
    'GenerationInProgress' : IDL.Null,
    'NodeNotFound' : IDL.Null,
    'InvalidSecretKey' : IDL.Null,
    'FolderNotFound' : IDL.Null,
    'Other' : IDL.Text,
    'TrialExpired' : IDL.Null,
    'RoleAlreadyClaimed' : IDL.Null,
    'UserNotFound' : IDL.Null,
  });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : CanisterError });
  const AddMeasurementRequest = IDL.Record({
    'name' : IDL.Text,
    'measurement_hex' : IDL.Text,
  });
  const ModelStatus = IDL.Variant({ 'Paused' : IDL.Null, 'Active' : IDL.Null });
  const Model = IDL.Record({
    'maker' : IDL.Text,
    'status' : ModelStatus,
    'max_tools' : IDL.Nat32,
    'max_output' : IDL.Nat32,
    'provider' : IDL.Text,
    'release_date' : IDL.Opt(IDL.Text),
    'extra_body_json' : IDL.Opt(IDL.Text),
    'max_image_attachments' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'output_token_price' : IDL.Float64,
    'provider_model' : IDL.Text,
    'provider_endpoint' : IDL.Text,
    'input_token_price' : IDL.Float64,
    'is_reasoning' : IDL.Bool,
    'model_id' : IDL.Text,
    'aa_score' : IDL.Opt(IDL.Nat32),
    'max_context' : IDL.Nat32,
  });
  const AddModelRequest = IDL.Record({ 'model' : Model });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : CanisterError });
  const ConfirmRegistrationRequest = IDL.Record({
    'user_principal' : IDL.Principal,
  });
  const CreateIndexNodeRequest = IDL.Record({
    'hostname' : IDL.Text,
    'encrypted_api_key' : IDL.Text,
    'model_id' : IDL.Text,
    'expected_chip_id' : IDL.Text,
  });
  const CreateIndexNodeResponse = IDL.Record({ 'node_id' : IDL.Nat64 });
  const Result_2 = IDL.Variant({
    'Ok' : CreateIndexNodeResponse,
    'Err' : CanisterError,
  });
  const CreateUserCanisterResponse = IDL.Record({
    'canister_id' : IDL.Principal,
  });
  const Result_3 = IDL.Variant({
    'Ok' : CreateUserCanisterResponse,
    'Err' : CanisterError,
  });
  const TcbVersion = IDL.Record({
    'fmc' : IDL.Nat8,
    'snp' : IDL.Nat8,
    'tee' : IDL.Nat8,
    'bootloader' : IDL.Nat8,
    'microcode' : IDL.Nat8,
  });
  const GenTcbRequirements = IDL.Record({
    'min_tcb' : TcbVersion,
    'min_guest_svn' : IDL.Nat32,
  });
  const MeasurementStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Deprecated' : IDL.Null,
    'Revoked' : IDL.Null,
  });
  const AttestationMeasurement = IDL.Record({
    'status' : MeasurementStatus,
    'updated_at' : IDL.Nat64,
    'name' : IDL.Text,
    'created_at' : IDL.Nat64,
    'measurement_hex' : IDL.Text,
  });
  const AttestationRequirements = IDL.Record({
    'max_attestation_age_ns' : IDL.Nat64,
    'min_report_version' : IDL.Nat32,
    'require_ciphertext_hiding_enabled' : IDL.Bool,
    'require_tsme_disabled' : IDL.Bool,
    'genoa_policy' : GenTcbRequirements,
    'expected_measurement_len' : IDL.Nat64,
    'measurements' : IDL.Vec(AttestationMeasurement),
    'require_ecc_enabled' : IDL.Bool,
    'require_smt_disabled' : IDL.Bool,
    'turin_policy' : GenTcbRequirements,
    'require_rapl_disabled' : IDL.Bool,
    'milan_policy' : GenTcbRequirements,
  });
  const GetAttestationRequirementsResponse = IDL.Record({
    'requirements' : AttestationRequirements,
  });
  const Result_4 = IDL.Variant({
    'Ok' : GetAttestationRequirementsResponse,
    'Err' : CanisterError,
  });
  const GetModelsResponse = IDL.Record({ 'models' : IDL.Vec(Model) });
  const GetNodeConfigRequest = IDL.Record({ 'node_id' : IDL.Nat64 });
  const GetNodeConfigResponse = IDL.Record({
    'hostname' : IDL.Text,
    'encrypted_api_key' : IDL.Text,
    'model_id' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'Ok' : GetNodeConfigResponse,
    'Err' : CanisterError,
  });
  const GetProvisioningInfoResponse = IDL.Record({
    'owner' : IDL.Principal,
    'hostname' : IDL.Text,
    'is_active' : IDL.Bool,
    'model_id' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'Ok' : GetProvisioningInfoResponse,
    'Err' : CanisterError,
  });
  const GetUserAssignmentRequest = IDL.Record({
    'user_principal' : IDL.Principal,
  });
  const GetUserAssignmentResponse = IDL.Record({
    'assigned_canister' : IDL.Vec(IDL.Principal),
  });
  const Result_7 = IDL.Variant({
    'Ok' : GetUserAssignmentResponse,
    'Err' : CanisterError,
  });
  const NodeHeartbeatCommand = IDL.Variant({
    'Continue' : IDL.Null,
    'Abort' : IDL.Null,
    'DrainAndShutdown' : IDL.Null,
  });
  const HeartbeatResponse = IDL.Record({ 'command' : NodeHeartbeatCommand });
  const Result_8 = IDL.Variant({
    'Ok' : HeartbeatResponse,
    'Err' : CanisterError,
  });
  const IsManagerResponse = IDL.Record({ 'is_manager' : IDL.Bool });
  const Result_9 = IDL.Variant({
    'Ok' : IsManagerResponse,
    'Err' : CanisterError,
  });
  const PublicNodeInfo = IDL.Record({
    'node_id' : IDL.Nat64,
    'public_key' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'detected_generation' : IDL.Opt(IDL.Text),
    'hostname' : IDL.Text,
    'attestation_verified_at' : IDL.Opt(IDL.Nat64),
    'reported_measurement_hex' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Bool,
    'model_id' : IDL.Text,
    'reported_chip_id_hex' : IDL.Opt(IDL.Text),
    'node_principal' : IDL.Opt(IDL.Principal),
    'last_heartbeat_timestamp' : IDL.Opt(IDL.Nat64),
  });
  const ListActiveNodesResponse = IDL.Record({
    'nodes' : IDL.Vec(PublicNodeInfo),
  });
  const Result_10 = IDL.Variant({
    'Ok' : ListActiveNodesResponse,
    'Err' : CanisterError,
  });
  const CanisterPoolState = IDL.Variant({
    'Available' : IDL.Null,
    'Assigned' : IDL.Record({
      'owner' : IDL.Principal,
      'expires_at' : IDL.Opt(IDL.Nat64),
    }),
  });
  const CanisterPoolEntry = IDL.Record({
    'time_created' : IDL.Nat64,
    'canister_id' : IDL.Principal,
    'state' : CanisterPoolState,
  });
  const ListCanisterPoolResponse = IDL.Record({
    'assigned' : IDL.Vec(CanisterPoolEntry),
    'available' : IDL.Vec(CanisterPoolEntry),
    'pool_target_size' : IDL.Nat32,
  });
  const Result_11 = IDL.Variant({
    'Ok' : ListCanisterPoolResponse,
    'Err' : CanisterError,
  });
  const ListManagersResponse = IDL.Record({
    'managers' : IDL.Vec(IDL.Principal),
  });
  const Result_12 = IDL.Variant({
    'Ok' : ListManagersResponse,
    'Err' : CanisterError,
  });
  const ListMyNodesResponse = IDL.Record({ 'nodes' : IDL.Vec(PublicNodeInfo) });
  const Result_13 = IDL.Variant({
    'Ok' : ListMyNodesResponse,
    'Err' : CanisterError,
  });
  const ListUserCanistersResponse = IDL.Record({
    'canisters' : IDL.Vec(CanisterPoolEntry),
  });
  const Result_14 = IDL.Variant({
    'Ok' : ListUserCanistersResponse,
    'Err' : CanisterError,
  });
  const ProvisionCanistersRequest = IDL.Record({ 'count' : IDL.Nat32 });
  const ProvisionCanistersResponse = IDL.Record({
    'pool_size' : IDL.Nat32,
    'canisters_created' : IDL.Nat32,
  });
  const Result_15 = IDL.Variant({
    'Ok' : ProvisionCanistersResponse,
    'Err' : CanisterError,
  });
  const RawWhoAmIResponse = IDL.Record({ 'principal' : IDL.Principal });
  const RegisterNodeRequest = IDL.Record({
    'attestation_report' : IDL.Vec(IDL.Nat8),
    'node_id' : IDL.Nat64,
    'ark_der' : IDL.Vec(IDL.Nat8),
    'public_key' : IDL.Text,
    'vek_der' : IDL.Vec(IDL.Nat8),
    'ask_der' : IDL.Vec(IDL.Nat8),
    'timestamp' : IDL.Nat64,
  });
  const RegisterNodeResponse = IDL.Record({ 'success' : IDL.Bool });
  const Result_16 = IDL.Variant({
    'Ok' : RegisterNodeResponse,
    'Err' : CanisterError,
  });
  const RegisterUserRequest = IDL.Record({ 'username' : IDL.Text });
  const RegisterUserResponse = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'user_id' : IDL.Nat64,
    'user_canister_id' : IDL.Principal,
  });
  const Result_17 = IDL.Variant({
    'Ok' : RegisterUserResponse,
    'Err' : CanisterError,
  });
  const RemoveManagerRequest = IDL.Record({
    'principal_to_remove' : IDL.Principal,
  });
  const RemoveMeasurementRequest = IDL.Record({ 'measurement_hex' : IDL.Text });
  const UpdateAttestationPoliciesRequest = IDL.Record({
    'max_attestation_age_ns' : IDL.Nat64,
    'min_report_version' : IDL.Nat32,
    'require_ciphertext_hiding_enabled' : IDL.Bool,
    'require_tsme_disabled' : IDL.Bool,
    'genoa_policy' : GenTcbRequirements,
    'expected_measurement_len' : IDL.Nat64,
    'require_ecc_enabled' : IDL.Bool,
    'require_smt_disabled' : IDL.Bool,
    'turin_policy' : GenTcbRequirements,
    'require_rapl_disabled' : IDL.Bool,
    'milan_policy' : GenTcbRequirements,
  });
  const UpdateMeasurementStatusRequest = IDL.Record({
    'status' : MeasurementStatus,
    'measurement_hex' : IDL.Text,
  });
  const WhoAmIResponse = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
  });
  
  return IDL.Service({
    'add_manager' : IDL.Func([AddManagerRequest], [Result], []),
    'add_measurement' : IDL.Func([AddMeasurementRequest], [Result], []),
    'add_model' : IDL.Func([AddModelRequest], [Result_1], []),
    'claim_manager_role' : IDL.Func([], [Result_1], []),
    'confirm_registration' : IDL.Func(
        [ConfirmRegistrationRequest],
        [Result_1],
        [],
      ),
    'create_node' : IDL.Func([CreateIndexNodeRequest], [Result_2], []),
    'create_user_canister' : IDL.Func([], [Result_3], []),
    'get_attestation_requirements' : IDL.Func(
        [IDL.Null],
        [Result_4],
        ['query'],
      ),
    'get_models' : IDL.Func([IDL.Null], [GetModelsResponse], ['query']),
    'get_node_config' : IDL.Func([GetNodeConfigRequest], [Result_5], ['query']),
    'get_provisioning_info' : IDL.Func(
        [GetNodeConfigRequest],
        [Result_6],
        ['query'],
      ),
    'get_user_assignment' : IDL.Func(
        [GetUserAssignmentRequest],
        [Result_7],
        ['query'],
      ),
    'heartbeat' : IDL.Func([IDL.Null], [Result_8], []),
    'is_manager' : IDL.Func([], [Result_9], ['query']),
    'list_active_nodes' : IDL.Func([IDL.Null], [Result_10], ['query']),
    'list_canister_pool' : IDL.Func([], [Result_11], ['query']),
    'list_managers' : IDL.Func([], [Result_12], ['query']),
    'list_my_nodes' : IDL.Func([IDL.Null], [Result_13], ['query']),
    'list_user_canisters' : IDL.Func([], [Result_14], ['query']),
    'provision_canisters' : IDL.Func(
        [ProvisionCanistersRequest],
        [Result_15],
        [],
      ),
    'raw_whoami' : IDL.Func([IDL.Null], [RawWhoAmIResponse], ['query']),
    'register_node' : IDL.Func([RegisterNodeRequest], [Result_16], []),
    'register_user' : IDL.Func([RegisterUserRequest], [Result_17], []),
    'remove_manager' : IDL.Func([RemoveManagerRequest], [Result_1], []),
    'remove_measurement' : IDL.Func([RemoveMeasurementRequest], [Result_1], []),
    'unregister_node' : IDL.Func([IDL.Null], [Result_1], []),
    'update_attestation_policies' : IDL.Func(
        [UpdateAttestationPoliciesRequest],
        [Result_1],
        [],
      ),
    'update_measurement_status' : IDL.Func(
        [UpdateMeasurementStatusRequest],
        [Result_1],
        [],
      ),
    'update_model' : IDL.Func([AddModelRequest], [Result_1], []),
    'whoami' : IDL.Func([IDL.Null], [WhoAmIResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };