/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddMessageRequest {
  'custom_prompt' : [] | [string],
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'content' : Uint8Array,
  'temperature' : number,
  'encrypted_chat_key' : [] | [string],
  'role' : Role,
  'parent_message_id' : [] | [bigint],
  'max_completion_tokens' : number,
  'reasoning_effort' : [] | [string],
  'model_id' : string,
  'chat_id' : bigint,
  'attachments' : [] | [Array<ImageAttachment>],
  'max_context' : number,
}
export interface AddMessageResponse {
  'job' : Job,
  'ai_message' : Message,
  'message' : Message,
}
export interface ArchiveChatRequest { 'chat_id' : bigint }
export interface ArchiveChatResponse { 'chat' : Chat }
export type CanisterError = { 'CannotDeleteRootFolder' : null } |
  { 'UserAlreadyRegistered' : null } |
  { 'InvalidFileName' : string } |
  { 'DeleteNonEmptyFolder' : null } |
  { 'ModelNotFound' : null } |
  { 'InvalidPathDepth' : null } |
  { 'InvalidInput' : string } |
  { 'UnsupportedMimeType' : string } |
  { 'PoolExhausted' : null } |
  { 'NoAvailableUserCanister' : null } |
  { 'MessageNotFound' : null } |
  { 'FileSystemLimitExceeded' : string } |
  { 'ChatNotFound' : null } |
  { 'Unauthorized' : null } |
  { 'FileNotFound' : null } |
  { 'CallError' : string } |
  { 'PathNotFound' : null } |
  { 'ItemNameCollision' : string } |
  { 'GenerationInProgress' : null } |
  { 'NodeNotFound' : null } |
  { 'InvalidSecretKey' : null } |
  { 'FolderNotFound' : null } |
  { 'Other' : string } |
  { 'TrialExpired' : null } |
  { 'RoleAlreadyClaimed' : null } |
  { 'UserNotFound' : null };
export interface Chat {
  'title' : string,
  'updated_at' : bigint,
  'owner' : Principal,
  'job_ids' : BigUint64Array,
  'created_at' : bigint,
  'message_ids' : BigUint64Array,
  'encryption_salt' : Uint8Array,
  'chat_id' : bigint,
  'temporary' : boolean,
  'active_job_id' : [] | [bigint],
  'archived' : boolean,
}
export interface ClaimJobRequest { 'job_id' : bigint }
export interface ClaimJobResponse {
  'job' : Job,
  'tools' : [] | [Array<Tool>],
  'chat' : Chat,
  'message_chain_ids' : BigUint64Array,
}
export interface CompleteJobRequest {
  'result' : JobCompletionResult,
  'job_id' : bigint,
  'usage' : [] | [TokenUsage],
}
export interface ContinueFromToolResponseRequest {
  'custom_prompt' : [] | [string],
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'responses' : Array<ToolResponseMessage>,
  'assistant_message_id' : bigint,
  'temperature' : number,
  'encrypted_chat_key' : [] | [string],
  'max_completion_tokens' : number,
  'reasoning_effort' : [] | [string],
  'model_id' : string,
  'chat_id' : bigint,
  'max_context' : number,
}
export interface ContinueFromToolResponseResponse {
  'new_ai_message_id' : bigint,
  'job_id' : bigint,
}
export interface CreateChatRequest {
  'custom_prompt' : [] | [string],
  'title' : string,
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'temperature' : number,
  'encrypted_chat_key' : [] | [string],
  'max_completion_tokens' : number,
  'initial_message' : Uint8Array,
  'encryption_salt' : Uint8Array,
  'model_id' : string,
  'temporary' : boolean,
  'attachments' : [] | [Array<ImageAttachment>],
  'max_context' : number,
}
export interface CreateChatResponse {
  'ai_message_id' : bigint,
  'job_id' : bigint,
  'chat_id' : bigint,
  'user_message_id' : bigint,
}
export interface CreateFolderRequest {
  'name' : string,
  'parent_folder_id' : bigint,
}
export interface CreateFolderResponse { 'folder' : FolderInfo }
export interface DeleteChatRequest { 'chat_id' : bigint }
export interface DeleteItemRequest {
  'item_type' : FsItemType,
  'item_id' : bigint,
}
export interface EditUserMessageRequest {
  'custom_prompt' : [] | [string],
  'old_user_message_id' : bigint,
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'temperature' : number,
  'encrypted_chat_key' : [] | [string],
  'max_completion_tokens' : number,
  'new_content' : Uint8Array,
  'reasoning_effort' : [] | [string],
  'model_id' : string,
  'chat_id' : bigint,
  'attachments' : [] | [Array<ImageAttachment>],
  'max_context' : number,
}
export interface EditUserMessageResponse {
  'job' : Job,
  'new_user_message' : Message,
  'new_ai_message' : Message,
}
export interface FileInfo {
  'id' : bigint,
  'updated_at' : bigint,
  'name' : string,
  'mime_type' : string,
  'created_at' : bigint,
  'parent_folder_id' : bigint,
  'content_size_bytes' : bigint,
  'chunks' : Array<TextChunk>,
}
export interface FinalizeRegistrationRequest {
  'enc_salt' : Uint8Array,
  'enc_validator' : string,
}
export interface FinalizeRegistrationResponse { 'success' : boolean }
export interface FolderInfo {
  'id' : bigint,
  'updated_at' : bigint,
  'name' : string,
  'created_at' : bigint,
}
export type FsItemInfo = { 'Folder' : FolderInfo } |
  { 'File' : FileInfo };
export type FsItemType = { 'Folder' : null } |
  { 'File' : null };
export interface FunctionCall { 'name' : string, 'arguments' : string }
export type GenerationStatus = { 'Failed' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface GetChatJobsResponse { 'jobs' : Array<Job> }
export interface GetChatRequest { 'chat_id' : bigint }
export interface GetChatResponse { 'chat' : Chat }
export interface GetFileContentRequest { 'file_id' : bigint }
export interface GetFileContentResponse {
  'content' : Uint8Array,
  'mime_type' : string,
}
export interface GetFolderContentRequest { 'folder_id' : [] | [bigint] }
export interface GetFolderContentResponse {
  'files' : Array<FileInfo>,
  'folder_name' : string,
  'folders' : Array<FolderInfo>,
  'parent_folder_id' : [] | [bigint],
  'folder_id' : bigint,
}
export interface GetItemByPathRequest { 'path' : string }
export interface GetItemByPathResponse { 'item' : FsItemInfo }
export interface GetMessageRequest { 'message_id' : bigint }
export interface GetMessageResponse { 'message' : Message }
export interface GetUserStorageUsageResponse {
  'limit_bytes' : bigint,
  'usage_bytes' : bigint,
}
export interface GptUserGetNodesResponse { 'nodes' : Array<LocalNode> }
export interface GptUserListRegisteredUsersResponse {
  'users' : Array<UserDetails>,
}
export interface ImageAttachment { 'data' : Uint8Array, 'mime_type' : string }
export interface IsUserFinalizedRequest { 'user_principal' : Principal }
export interface IsUserFinalizedResponse { 'is_finalized' : boolean }
export interface Job {
  'custom_prompt' : [] | [string],
  'updated_at' : bigint,
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'temperature' : number,
  'extra_body_json' : [] | [string],
  'encrypted_chat_key' : [] | [string],
  'created_at' : bigint,
  'max_completion_tokens' : number,
  'job_id' : bigint,
  'placeholder_message_id' : bigint,
  'reasoning_effort' : [] | [string],
  'model_id' : string,
  'chat_id' : bigint,
  'generation_status' : GenerationStatus,
  'max_context' : number,
}
export type JobCompletionResult = { 'Success' : Uint8Array } |
  { 'ToolCall' : Array<ToolCall> } |
  { 'Failure' : MessageErrorStatus };
export interface ListChatsRequest { 'include_archived' : boolean }
export interface ListChatsResponse { 'chats' : Array<Chat> }
export interface LocalNode {
  'node_id' : bigint,
  'public_key' : [] | [string],
  'address' : string,
  'model_id' : string,
  'node_principal' : [] | [Principal],
}
export interface Message {
  'updated_at' : bigint,
  'content' : Uint8Array,
  'tool_calls' : [] | [Array<ToolCall>],
  'role' : Role,
  'parent_message_id' : [] | [bigint],
  'error_status' : [] | [MessageErrorStatus],
  'created_at' : bigint,
  'tool_call_id' : [] | [string],
  'requires_client_action' : boolean,
  'usage' : [] | [TokenUsage],
  'tool_results' : [] | [Array<ToolResult>],
  'chat_id' : bigint,
  'message_id' : bigint,
  'attachments' : [] | [Array<ImageAttachment>],
}
export type MessageErrorStatus = { 'NodeOffline' : null } |
  { 'ProviderError' : ProviderErrorType } |
  { 'Timeout' : null } |
  { 'Unknown' : string } |
  { 'ConfigurationError' : string } |
  { 'CanisterCallError' : string } |
  { 'InvalidState' : string };
export interface NodeGetMessageRequest { 'message_id' : bigint }
export interface NodeGetMessageResponse { 'message' : Message }
export type ProviderErrorType = { 'InvalidImage' : string } |
  { 'NetworkError' : null } |
  { 'ContentPolicyViolation' : null } |
  { 'ContextLengthExceeded' : null } |
  { 'ServiceUnavailable' : null } |
  { 'RateLimited' : null } |
  { 'Timeout' : null } |
  { 'Unknown' : string } |
  { 'AuthenticationError' : null } |
  { 'BadRequest' : null } |
  { 'ServerError' : null };
export interface RenameChatRequest { 'new_title' : string, 'chat_id' : bigint }
export interface RenameItemRequest {
  'item_type' : FsItemType,
  'new_name' : string,
  'item_id' : bigint,
}
export interface RenameItemResponse { 'item' : FsItemInfo }
export type Result = { 'Ok' : AddMessageResponse } |
  { 'Err' : CanisterError };
export type Result_1 = { 'Ok' : ArchiveChatResponse } |
  { 'Err' : CanisterError };
export type Result_10 = { 'Ok' : GetChatResponse } |
  { 'Err' : CanisterError };
export type Result_11 = { 'Ok' : GetChatJobsResponse } |
  { 'Err' : CanisterError };
export type Result_12 = { 'Ok' : GetFileContentResponse } |
  { 'Err' : CanisterError };
export type Result_13 = { 'Ok' : GetFolderContentResponse } |
  { 'Err' : CanisterError };
export type Result_14 = { 'Ok' : GetItemByPathResponse } |
  { 'Err' : CanisterError };
export type Result_15 = { 'Ok' : GetMessageResponse } |
  { 'Err' : CanisterError };
export type Result_16 = { 'Ok' : GptUserGetNodesResponse } |
  { 'Err' : CanisterError };
export type Result_17 = { 'Ok' : GetUserStorageUsageResponse } |
  { 'Err' : CanisterError };
export type Result_18 = { 'Ok' : ListChatsResponse } |
  { 'Err' : CanisterError };
export type Result_19 = { 'Ok' : GptUserListRegisteredUsersResponse } |
  { 'Err' : CanisterError };
export type Result_2 = { 'Ok' : ClaimJobResponse } |
  { 'Err' : CanisterError };
export type Result_20 = { 'Ok' : NodeGetMessageResponse } |
  { 'Err' : CanisterError };
export type Result_21 = { 'Ok' : RenameItemResponse } |
  { 'Err' : CanisterError };
export type Result_22 = { 'Ok' : RetryAiMessageResponse } |
  { 'Err' : CanisterError };
export type Result_23 = { 'Ok' : UploadFileResponse } |
  { 'Err' : CanisterError };
export type Result_3 = { 'Ok' : null } |
  { 'Err' : CanisterError };
export type Result_4 = { 'Ok' : ContinueFromToolResponseResponse } |
  { 'Err' : CanisterError };
export type Result_5 = { 'Ok' : CreateChatResponse } |
  { 'Err' : CanisterError };
export type Result_6 = { 'Ok' : CreateFolderResponse } |
  { 'Err' : CanisterError };
export type Result_7 = { 'Ok' : null } |
  { 'Err' : CanisterError };
export type Result_8 = { 'Ok' : EditUserMessageResponse } |
  { 'Err' : CanisterError };
export type Result_9 = { 'Ok' : FinalizeRegistrationResponse } |
  { 'Err' : CanisterError };
export interface RetryAiMessageRequest {
  'custom_prompt' : [] | [string],
  'tools' : [] | [Array<Tool>],
  'node_id' : bigint,
  'temperature' : number,
  'encrypted_chat_key' : [] | [string],
  'max_completion_tokens' : number,
  'reasoning_effort' : [] | [string],
  'model_id' : string,
  'chat_id' : bigint,
  'max_context' : number,
  'user_message_id' : bigint,
}
export interface RetryAiMessageResponse {
  'job' : Job,
  'new_ai_message' : Message,
}
export type Role = { 'System' : null } |
  { 'Tool' : null } |
  { 'User' : null } |
  { 'Assistant' : null };
export interface StoreToolResultsRequest {
  'assistant_message_id' : bigint,
  'results' : Array<ToolResult>,
  'chat_id' : bigint,
}
export interface TextChunk {
  'chunk_index' : number,
  'end_char' : number,
  'start_char' : number,
  'embedding' : Uint8Array,
}
export interface TokenUsage {
  'completion_tokens' : number,
  'prompt_tokens' : number,
  'total_tokens' : number,
}
export interface Tool {
  'name' : string,
  'parameters' : string,
  'description' : string,
}
export interface ToolCall {
  'id' : string,
  'function' : FunctionCall,
  'type' : string,
}
export interface ToolResponseMessage {
  'content' : string,
  'tool_call_id' : string,
}
export interface ToolResult {
  'content' : string,
  'error' : [] | [string],
  'tool_call_id' : string,
}
export interface UpdateMessageAttachmentsRequest {
  'message_id' : bigint,
  'attachments' : [] | [Array<ImageAttachment>],
}
export interface UploadFileRequest {
  'content' : Uint8Array,
  'name' : string,
  'mime_type' : string,
  'parent_folder_id' : bigint,
  'chunks' : [] | [Array<TextChunk>],
}
export interface UploadFileResponse { 'file' : FileInfo }
export interface UserDetails {
  'enc_salt' : [] | [Uint8Array],
  'principal' : Principal,
  'enc_validator' : [] | [string],
  'registered_at' : bigint,
}
export interface WhoAmIUserResponse {
  'enc_salt' : [] | [Uint8Array],
  'principal' : Principal,
  'enc_validator' : [] | [string],
}
export interface _SERVICE {
  /**
   * The public update method for a user to add a new message to a chat.
   */
  'add_message' : ActorMethod<[AddMessageRequest], Result>,
  'archive_chat' : ActorMethod<[ArchiveChatRequest], Result_1>,
  'claim_job' : ActorMethod<[ClaimJobRequest], Result_2>,
  /**
   * The public update method for a node to submit the result of a generation job.
   */
  'complete_job' : ActorMethod<[CompleteJobRequest], Result_3>,
  'continue_from_tool_response' : ActorMethod<
    [ContinueFromToolResponseRequest],
    Result_4
  >,
  'create_chat' : ActorMethod<[CreateChatRequest], Result_5>,
  'create_folder' : ActorMethod<[CreateFolderRequest], Result_6>,
  'delete_chat' : ActorMethod<[DeleteChatRequest], Result_3>,
  'delete_item' : ActorMethod<[DeleteItemRequest], Result_7>,
  'edit_user_message' : ActorMethod<[EditUserMessageRequest], Result_8>,
  'finalize_registration' : ActorMethod<
    [FinalizeRegistrationRequest],
    Result_9
  >,
  'get_chat' : ActorMethod<[GetChatRequest], Result_10>,
  'get_chat_jobs' : ActorMethod<[GetChatRequest], Result_11>,
  'get_file_content' : ActorMethod<[GetFileContentRequest], Result_12>,
  'get_folder_content' : ActorMethod<[GetFolderContentRequest], Result_13>,
  'get_item_by_path' : ActorMethod<[GetItemByPathRequest], Result_14>,
  'get_message' : ActorMethod<[GetMessageRequest], Result_15>,
  'get_nodes' : ActorMethod<[], Result_16>,
  'get_user_storage_usage' : ActorMethod<[], Result_17>,
  /**
   * Checks if a user is finalized (i.e., the canister is bound to them with vault data).
   * For a single-user canister, this checks if the owner matches and has vault data.
   */
  'is_user_finalized' : ActorMethod<
    [IsUserFinalizedRequest],
    IsUserFinalizedResponse
  >,
  'list_chats' : ActorMethod<[ListChatsRequest], Result_18>,
  /**
   * Returns the single owner of this canister (if bound).
   * For a single-user canister, this returns a list with at most one user.
   */
  'list_registered_users' : ActorMethod<[], Result_19>,
  'node_get_message' : ActorMethod<[NodeGetMessageRequest], Result_20>,
  'rename_chat' : ActorMethod<[RenameChatRequest], Result_10>,
  'rename_item' : ActorMethod<[RenameItemRequest], Result_21>,
  'retry_ai_message' : ActorMethod<[RetryAiMessageRequest], Result_22>,
  'store_tool_results' : ActorMethod<[StoreToolResultsRequest], Result_7>,
  'unarchive_chat' : ActorMethod<[GetChatRequest], Result_10>,
  'update_message_attachments' : ActorMethod<
    [UpdateMessageAttachmentsRequest],
    Result_7
  >,
  'upload_file' : ActorMethod<[UploadFileRequest], Result_23>,
  /**
   * Returns the caller's identity and vault data.
   * For a single-user canister, this returns the bound owner's details.
   */
  'whoami' : ActorMethod<[], WhoAmIUserResponse>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];