import {
  ArrowDown,
  ArrowUp,
  Barricade,
  Bookmarks,
  CaretDown,
  Check,
  Cloud,
  Code,
  Cpu,
  Dot,
  DotsThree,
  FileCode,
  FileSearchIcon,
  Files,
  FileText,
  Flask,
  Folder,
  Folders,
  Gavel,
  Globe,
  GlobeX,
  GoogleLogo,
  HardDrive,
  HardDrives,
  ImageSquare,
  Info,
  Lightbulb,
  Link,
  LinkSimple,
  MagnifyingGlass,
  MetaLogo,
  NotePencil,
  OpenAiLogo,
  Paperclip,
  Question,
  Robot,
  SlidersHorizontal,
  Star,
  TextAlignCenter,
  User,
  WifiX,
  XCircle,
  Wrench,
  CalendarBlank,
} from "@phosphor-icons/react";

import {
  DeepSeekLogo,
  QwenLogo,
  MistralLogo,
  XAiLogo,
  MoonshotLogo,
} from "./Logos";

export const Icons = {
  dot: Dot,
  offline: WifiX,
  online: Globe,
  documents: Files,
  caretDown: CaretDown,
  globeX: GlobeX,
  openai: OpenAiLogo,
  meta: MetaLogo,
  google: GoogleLogo,
  mistral: MistralLogo,
  qwen: QwenLogo,
  deepseek: DeepSeekLogo,
  xai: XAiLogo,
  moonshotai: MoonshotLogo,
  notePencil: NotePencil,
  slidersHorizontal: SlidersHorizontal,
  arrowDown: ArrowDown,
  drives: HardDrives,
  drive: HardDrive,
  arrowUp: ArrowUp,
  xCircle: XCircle,
  dotsThree: DotsThree,
  check: Check,
  question: Question,
  code: Code,
  search: MagnifyingGlass,
  folders: Folders,
  user: User,
  info: Info,
  folder: Folder,
  link: LinkSimple,
  bridge: Link,
  bookmarks: Bookmarks,
  cloud: Cloud,
  paperclip: Paperclip,
  globe: Globe,
  star: Star,
  barricade: Barricade,
  flask: Flask,
  fileCode: FileCode,
  fileSearch: FileSearchIcon,
  fileText: FileText,
  imageSquare: ImageSquare,
  lightbulb: Lightbulb,
  cpu: Cpu,
  robot: Robot,
  wrench: Wrench,
  calendar: CalendarBlank,
  textAlignCenter: TextAlignCenter,
  gavel: Gavel,
} as const;

export const ModelIcons = {
  openai: Icons.openai,
  meta: Icons.meta,
  google: Icons.google,
  mistral: Icons.mistral,
  qwen: Icons.qwen,
  deepseek: Icons.deepseek,
  xai: Icons.xai,
  moonshotai: Icons.moonshotai,
  perplexity: Icons.robot,
  anthropic: Icons.robot,
} as const;

export type IconsType = typeof Icons;
export type ModelIconsType = typeof ModelIcons;
