/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/gpt_index.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface AttestationMeasurement {
    status: MeasurementStatus;
    updated_at: bigint;
    name: string;
    created_at: bigint;
    measurement_hex: string;
}
export interface RegisterUserRequest {
    username: string;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: CreateIndexNodeResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface RemoveMeasurementRequest {
    measurement_hex: string;
}
export interface GetNodeConfigResponse {
    hostname: string;
    encrypted_api_key: string;
    model_id: string;
}
export interface TcbVersion {
    fmc: number;
    snp: number;
    tee: number;
    bootloader: number;
    microcode: number;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: GetNodeConfigResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface IsManagerResponse {
    is_manager: boolean;
}
export interface GetModelsResponse {
    models: Array<Model>;
}
export interface CanisterPoolEntry {
    time_created: bigint;
    canister_id: Principal;
    state: CanisterPoolState;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: GetAttestationRequirementsResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface RawWhoAmIResponse {
    principal: Principal;
}
export type Result_7 = {
    __kind__: "Ok";
    Ok: GetUserAssignmentResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface GenTcbRequirements {
    min_tcb: TcbVersion;
    min_guest_svn: number;
}
export interface GetProvisioningInfoResponse {
    owner: Principal;
    hostname: string;
    is_active: boolean;
    model_id: string;
}
export type CanisterError = {
    __kind__: "CannotDeleteRootFolder";
    CannotDeleteRootFolder: null;
} | {
    __kind__: "UserAlreadyRegistered";
    UserAlreadyRegistered: null;
} | {
    __kind__: "InvalidFileName";
    InvalidFileName: string;
} | {
    __kind__: "DeleteNonEmptyFolder";
    DeleteNonEmptyFolder: null;
} | {
    __kind__: "ModelNotFound";
    ModelNotFound: null;
} | {
    __kind__: "InvalidPathDepth";
    InvalidPathDepth: null;
} | {
    __kind__: "InvalidInput";
    InvalidInput: string;
} | {
    __kind__: "UnsupportedMimeType";
    UnsupportedMimeType: string;
} | {
    __kind__: "PoolExhausted";
    PoolExhausted: null;
} | {
    __kind__: "NoAvailableUserCanister";
    NoAvailableUserCanister: null;
} | {
    __kind__: "MessageNotFound";
    MessageNotFound: null;
} | {
    __kind__: "FileSystemLimitExceeded";
    FileSystemLimitExceeded: string;
} | {
    __kind__: "ChatNotFound";
    ChatNotFound: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "FileNotFound";
    FileNotFound: null;
} | {
    __kind__: "CallError";
    CallError: string;
} | {
    __kind__: "PathNotFound";
    PathNotFound: null;
} | {
    __kind__: "ItemNameCollision";
    ItemNameCollision: string;
} | {
    __kind__: "GenerationInProgress";
    GenerationInProgress: null;
} | {
    __kind__: "NodeNotFound";
    NodeNotFound: null;
} | {
    __kind__: "InvalidSecretKey";
    InvalidSecretKey: null;
} | {
    __kind__: "FolderNotFound";
    FolderNotFound: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "TrialExpired";
    TrialExpired: null;
} | {
    __kind__: "RoleAlreadyClaimed";
    RoleAlreadyClaimed: null;
} | {
    __kind__: "UserNotFound";
    UserNotFound: null;
};
export interface RegisterUserResponse {
    principal: Principal;
    username: string;
    user_id: bigint;
    user_canister_id: Principal;
}
export interface ProvisionCanistersResponse {
    pool_size: number;
    canisters_created: number;
}
export type Result_6 = {
    __kind__: "Ok";
    Ok: GetProvisioningInfoResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface GetUserAssignmentRequest {
    user_principal: Principal;
}
export interface RemoveManagerRequest {
    principal_to_remove: Principal;
}
export type Result_12 = {
    __kind__: "Ok";
    Ok: ListManagersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export type Result_9 = {
    __kind__: "Ok";
    Ok: IsManagerResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface AddManagerRequest {
    principal_to_add: Principal;
}
export interface HeartbeatResponse {
    command: NodeHeartbeatCommand;
}
export interface PublicNodeInfo {
    node_id: bigint;
    public_key?: string;
    owner: Principal;
    detected_generation?: string;
    hostname: string;
    attestation_verified_at?: bigint;
    reported_measurement_hex?: string;
    is_active: boolean;
    model_id: string;
    reported_chip_id_hex?: string;
    node_principal?: Principal;
    last_heartbeat_timestamp?: bigint;
}
export type Result = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export type Result_10 = {
    __kind__: "Ok";
    Ok: ListActiveNodesResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export type Result_8 = {
    __kind__: "Ok";
    Ok: HeartbeatResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface ConfirmRegistrationRequest {
    user_principal: Principal;
}
export interface GetAttestationRequirementsResponse {
    requirements: AttestationRequirements;
}
export interface AttestationRequirements {
    max_attestation_age_ns: bigint;
    min_report_version: number;
    require_ciphertext_hiding_enabled: boolean;
    require_tsme_disabled: boolean;
    genoa_policy: GenTcbRequirements;
    expected_measurement_len: bigint;
    measurements: Array<AttestationMeasurement>;
    require_ecc_enabled: boolean;
    require_smt_disabled: boolean;
    turin_policy: GenTcbRequirements;
    require_rapl_disabled: boolean;
    milan_policy: GenTcbRequirements;
}
export type Result_17 = {
    __kind__: "Ok";
    Ok: RegisterUserResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export type Result_13 = {
    __kind__: "Ok";
    Ok: ListMyNodesResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface CreateIndexNodeResponse {
    node_id: bigint;
}
export interface WhoAmIResponse {
    principal: Principal;
    username: string;
}
export interface RegisterNodeRequest {
    attestation_report: Uint8Array;
    node_id: bigint;
    ark_der: Uint8Array;
    public_key: string;
    vek_der: Uint8Array;
    ask_der: Uint8Array;
    timestamp: bigint;
}
export type Result_16 = {
    __kind__: "Ok";
    Ok: RegisterNodeResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface ListActiveNodesResponse {
    nodes: Array<PublicNodeInfo>;
}
export interface ProvisionCanistersRequest {
    count: number;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export type Result_11 = {
    __kind__: "Ok";
    Ok: ListCanisterPoolResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface GetNodeConfigRequest {
    node_id: bigint;
}
export type Result_14 = {
    __kind__: "Ok";
    Ok: ListUserCanistersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface GetUserAssignmentResponse {
    assigned_canister: Array<Principal>;
}
export interface ListMyNodesResponse {
    nodes: Array<PublicNodeInfo>;
}
export interface RegisterNodeResponse {
    success: boolean;
}
export type CanisterPoolState = {
    __kind__: "Available";
    Available: null;
} | {
    __kind__: "Assigned";
    Assigned: {
        owner: Principal;
        expires_at?: bigint;
    };
};
export interface ListUserCanistersResponse {
    canisters: Array<CanisterPoolEntry>;
}
export interface CreateUserCanisterResponse {
    canister_id: Principal;
}
export interface UpdateMeasurementStatusRequest {
    status: MeasurementStatus;
    measurement_hex: string;
}
export interface AddModelRequest {
    model: Model;
}
export interface UpdateAttestationPoliciesRequest {
    max_attestation_age_ns: bigint;
    min_report_version: number;
    require_ciphertext_hiding_enabled: boolean;
    require_tsme_disabled: boolean;
    genoa_policy: GenTcbRequirements;
    expected_measurement_len: bigint;
    require_ecc_enabled: boolean;
    require_smt_disabled: boolean;
    turin_policy: GenTcbRequirements;
    require_rapl_disabled: boolean;
    milan_policy: GenTcbRequirements;
}
export type Result_3 = {
    __kind__: "Ok";
    Ok: CreateUserCanisterResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface ListCanisterPoolResponse {
    assigned: Array<CanisterPoolEntry>;
    available: Array<CanisterPoolEntry>;
    pool_target_size: number;
}
export interface ListManagersResponse {
    managers: Array<Principal>;
}
export type Result_15 = {
    __kind__: "Ok";
    Ok: ProvisionCanistersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
};
export interface AddMeasurementRequest {
    name: string;
    measurement_hex: string;
}
export interface CreateIndexNodeRequest {
    hostname: string;
    encrypted_api_key: string;
    model_id: string;
    expected_chip_id: string;
}
export interface Model {
    maker: string;
    status: ModelStatus;
    max_tools: number;
    max_output: number;
    provider: string;
    release_date?: string;
    extra_body_json?: string;
    max_image_attachments: number;
    name: string;
    description: string;
    output_token_price: number;
    provider_model: string;
    provider_endpoint: string;
    is_featured: boolean;
    input_token_price: number;
    is_reasoning: boolean;
    model_id: string;
    aa_score?: number;
    is_embedding: boolean;
    max_context: number;
}
export enum MeasurementStatus {
    Active = "Active",
    Deprecated = "Deprecated",
    Revoked = "Revoked"
}
export enum ModelStatus {
    Paused = "Paused",
    Active = "Active"
}
export enum NodeHeartbeatCommand {
    Continue = "Continue",
    Abort = "Abort",
    DrainAndShutdown = "DrainAndShutdown"
}
export interface gpt_indexInterface {
    add_manager(arg0: AddManagerRequest): Promise<Result>;
    add_measurement(arg0: AddMeasurementRequest): Promise<Result>;
    add_model(arg0: AddModelRequest): Promise<Result_1>;
    claim_manager_role(): Promise<Result_1>;
    confirm_registration(arg0: ConfirmRegistrationRequest): Promise<Result_1>;
    create_node(arg0: CreateIndexNodeRequest): Promise<Result_2>;
    create_user_canister(): Promise<Result_3>;
    get_attestation_requirements(arg0: null): Promise<Result_4>;
    get_models(arg0: null): Promise<GetModelsResponse>;
    get_node_config(arg0: GetNodeConfigRequest): Promise<Result_5>;
    get_provisioning_info(arg0: GetNodeConfigRequest): Promise<Result_6>;
    get_user_assignment(arg0: GetUserAssignmentRequest): Promise<Result_7>;
    heartbeat(arg0: null): Promise<Result_8>;
    is_manager(): Promise<Result_9>;
    list_active_nodes(arg0: null): Promise<Result_10>;
    list_canister_pool(): Promise<Result_11>;
    list_managers(): Promise<Result_12>;
    list_my_nodes(arg0: null): Promise<Result_13>;
    list_user_canisters(): Promise<Result_14>;
    provision_canisters(arg0: ProvisionCanistersRequest): Promise<Result_15>;
    raw_whoami(arg0: null): Promise<RawWhoAmIResponse>;
    register_node(arg0: RegisterNodeRequest): Promise<Result_16>;
    register_user(arg0: RegisterUserRequest): Promise<Result_17>;
    remove_manager(arg0: RemoveManagerRequest): Promise<Result_1>;
    remove_measurement(arg0: RemoveMeasurementRequest): Promise<Result_1>;
    unregister_node(arg0: null): Promise<Result_1>;
    update_attestation_policies(arg0: UpdateAttestationPoliciesRequest): Promise<Result_1>;
    update_measurement_status(arg0: UpdateMeasurementStatusRequest): Promise<Result_1>;
    update_model(arg0: AddModelRequest): Promise<Result_1>;
    whoami(arg0: null): Promise<WhoAmIResponse>;
}
import type { AddModelRequest as _AddModelRequest, AttestationMeasurement as _AttestationMeasurement, AttestationRequirements as _AttestationRequirements, CanisterError as _CanisterError, CanisterPoolEntry as _CanisterPoolEntry, CanisterPoolState as _CanisterPoolState, CreateIndexNodeResponse as _CreateIndexNodeResponse, CreateUserCanisterResponse as _CreateUserCanisterResponse, GenTcbRequirements as _GenTcbRequirements, GetAttestationRequirementsResponse as _GetAttestationRequirementsResponse, GetModelsResponse as _GetModelsResponse, GetNodeConfigResponse as _GetNodeConfigResponse, GetProvisioningInfoResponse as _GetProvisioningInfoResponse, GetUserAssignmentResponse as _GetUserAssignmentResponse, HeartbeatResponse as _HeartbeatResponse, IsManagerResponse as _IsManagerResponse, ListActiveNodesResponse as _ListActiveNodesResponse, ListCanisterPoolResponse as _ListCanisterPoolResponse, ListManagersResponse as _ListManagersResponse, ListMyNodesResponse as _ListMyNodesResponse, ListUserCanistersResponse as _ListUserCanistersResponse, MeasurementStatus as _MeasurementStatus, Model as _Model, ModelStatus as _ModelStatus, NodeHeartbeatCommand as _NodeHeartbeatCommand, ProvisionCanistersResponse as _ProvisionCanistersResponse, PublicNodeInfo as _PublicNodeInfo, RegisterNodeResponse as _RegisterNodeResponse, RegisterUserResponse as _RegisterUserResponse, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_13 as _Result_13, Result_14 as _Result_14, Result_15 as _Result_15, Result_16 as _Result_16, Result_17 as _Result_17, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, UpdateMeasurementStatusRequest as _UpdateMeasurementStatusRequest } from "./declarations/gpt_index.did.d.ts";
export class Gpt_index implements gpt_indexInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async add_manager(arg0: AddManagerRequest): Promise<Result> {
        const result = await this.actor.add_manager(arg0);
        return from_candid_Result_n1(result);
    }
    async add_measurement(arg0: AddMeasurementRequest): Promise<Result> {
        const result = await this.actor.add_measurement(arg0);
        return from_candid_Result_n1(result);
    }
    async add_model(arg0: AddModelRequest): Promise<Result_1> {
        const result = await this.actor.add_model(to_candid_AddModelRequest_n5(arg0));
        return from_candid_Result_1_n11(result);
    }
    async claim_manager_role(): Promise<Result_1> {
        const result = await this.actor.claim_manager_role();
        return from_candid_Result_1_n11(result);
    }
    async confirm_registration(arg0: ConfirmRegistrationRequest): Promise<Result_1> {
        const result = await this.actor.confirm_registration(arg0);
        return from_candid_Result_1_n11(result);
    }
    async create_node(arg0: CreateIndexNodeRequest): Promise<Result_2> {
        const result = await this.actor.create_node(arg0);
        return from_candid_Result_2_n12(result);
    }
    async create_user_canister(): Promise<Result_3> {
        const result = await this.actor.create_user_canister();
        return from_candid_Result_3_n14(result);
    }
    async get_attestation_requirements(arg0: null): Promise<Result_4> {
        const result = await this.actor.get_attestation_requirements(arg0);
        return from_candid_Result_4_n16(result);
    }
    async get_models(arg0: null): Promise<GetModelsResponse> {
        const result = await this.actor.get_models(arg0);
        return from_candid_GetModelsResponse_n27(result);
    }
    async get_node_config(arg0: GetNodeConfigRequest): Promise<Result_5> {
        const result = await this.actor.get_node_config(arg0);
        return from_candid_Result_5_n36(result);
    }
    async get_provisioning_info(arg0: GetNodeConfigRequest): Promise<Result_6> {
        const result = await this.actor.get_provisioning_info(arg0);
        return from_candid_Result_6_n38(result);
    }
    async get_user_assignment(arg0: GetUserAssignmentRequest): Promise<Result_7> {
        const result = await this.actor.get_user_assignment(arg0);
        return from_candid_Result_7_n40(result);
    }
    async heartbeat(arg0: null): Promise<Result_8> {
        const result = await this.actor.heartbeat(arg0);
        return from_candid_Result_8_n42(result);
    }
    async is_manager(): Promise<Result_9> {
        const result = await this.actor.is_manager();
        return from_candid_Result_9_n48(result);
    }
    async list_active_nodes(arg0: null): Promise<Result_10> {
        const result = await this.actor.list_active_nodes(arg0);
        return from_candid_Result_10_n50(result);
    }
    async list_canister_pool(): Promise<Result_11> {
        const result = await this.actor.list_canister_pool();
        return from_candid_Result_11_n59(result);
    }
    async list_managers(): Promise<Result_12> {
        const result = await this.actor.list_managers();
        return from_candid_Result_12_n69(result);
    }
    async list_my_nodes(arg0: null): Promise<Result_13> {
        const result = await this.actor.list_my_nodes(arg0);
        return from_candid_Result_13_n71(result);
    }
    async list_user_canisters(): Promise<Result_14> {
        const result = await this.actor.list_user_canisters();
        return from_candid_Result_14_n74(result);
    }
    async provision_canisters(arg0: ProvisionCanistersRequest): Promise<Result_15> {
        const result = await this.actor.provision_canisters(arg0);
        return from_candid_Result_15_n78(result);
    }
    async raw_whoami(arg0: null): Promise<RawWhoAmIResponse> {
        const result = await this.actor.raw_whoami(arg0);
        return result;
    }
    async register_node(arg0: RegisterNodeRequest): Promise<Result_16> {
        const result = await this.actor.register_node(arg0);
        return from_candid_Result_16_n80(result);
    }
    async register_user(arg0: RegisterUserRequest): Promise<Result_17> {
        const result = await this.actor.register_user(arg0);
        return from_candid_Result_17_n82(result);
    }
    async remove_manager(arg0: RemoveManagerRequest): Promise<Result_1> {
        const result = await this.actor.remove_manager(arg0);
        return from_candid_Result_1_n11(result);
    }
    async remove_measurement(arg0: RemoveMeasurementRequest): Promise<Result_1> {
        const result = await this.actor.remove_measurement(arg0);
        return from_candid_Result_1_n11(result);
    }
    async unregister_node(arg0: null): Promise<Result_1> {
        const result = await this.actor.unregister_node(arg0);
        return from_candid_Result_1_n11(result);
    }
    async update_attestation_policies(arg0: UpdateAttestationPoliciesRequest): Promise<Result_1> {
        const result = await this.actor.update_attestation_policies(arg0);
        return from_candid_Result_1_n11(result);
    }
    async update_measurement_status(arg0: UpdateMeasurementStatusRequest): Promise<Result_1> {
        const result = await this.actor.update_measurement_status(to_candid_UpdateMeasurementStatusRequest_n84(arg0));
        return from_candid_Result_1_n11(result);
    }
    async update_model(arg0: AddModelRequest): Promise<Result_1> {
        const result = await this.actor.update_model(to_candid_AddModelRequest_n5(arg0));
        return from_candid_Result_1_n11(result);
    }
    async whoami(arg0: null): Promise<WhoAmIResponse> {
        const result = await this.actor.whoami(arg0);
        return result;
    }
}
function from_candid_AttestationMeasurement_n23(value: _AttestationMeasurement): AttestationMeasurement {
    return from_candid_record_n24(value);
}
function from_candid_AttestationRequirements_n20(value: _AttestationRequirements): AttestationRequirements {
    return from_candid_record_n21(value);
}
function from_candid_CanisterError_n3(value: _CanisterError): CanisterError {
    return from_candid_variant_n4(value);
}
function from_candid_CanisterPoolEntry_n64(value: _CanisterPoolEntry): CanisterPoolEntry {
    return from_candid_record_n65(value);
}
function from_candid_CanisterPoolState_n66(value: _CanisterPoolState): CanisterPoolState {
    return from_candid_variant_n67(value);
}
function from_candid_GetAttestationRequirementsResponse_n18(value: _GetAttestationRequirementsResponse): GetAttestationRequirementsResponse {
    return from_candid_record_n19(value);
}
function from_candid_GetModelsResponse_n27(value: _GetModelsResponse): GetModelsResponse {
    return from_candid_record_n28(value);
}
function from_candid_HeartbeatResponse_n44(value: _HeartbeatResponse): HeartbeatResponse {
    return from_candid_record_n45(value);
}
function from_candid_ListActiveNodesResponse_n52(value: _ListActiveNodesResponse): ListActiveNodesResponse {
    return from_candid_record_n53(value);
}
function from_candid_ListCanisterPoolResponse_n61(value: _ListCanisterPoolResponse): ListCanisterPoolResponse {
    return from_candid_record_n62(value);
}
function from_candid_ListMyNodesResponse_n73(value: _ListMyNodesResponse): ListMyNodesResponse {
    return from_candid_record_n53(value);
}
function from_candid_ListUserCanistersResponse_n76(value: _ListUserCanistersResponse): ListUserCanistersResponse {
    return from_candid_record_n77(value);
}
function from_candid_MeasurementStatus_n25(value: _MeasurementStatus): MeasurementStatus {
    return from_candid_variant_n26(value);
}
function from_candid_ModelStatus_n32(value: _ModelStatus): ModelStatus {
    return from_candid_variant_n33(value);
}
function from_candid_Model_n30(value: _Model): Model {
    return from_candid_record_n31(value);
}
function from_candid_NodeHeartbeatCommand_n46(value: _NodeHeartbeatCommand): NodeHeartbeatCommand {
    return from_candid_variant_n47(value);
}
function from_candid_PublicNodeInfo_n55(value: _PublicNodeInfo): PublicNodeInfo {
    return from_candid_record_n56(value);
}
function from_candid_Result_10_n50(value: _Result_10): Result_10 {
    return from_candid_variant_n51(value);
}
function from_candid_Result_11_n59(value: _Result_11): Result_11 {
    return from_candid_variant_n60(value);
}
function from_candid_Result_12_n69(value: _Result_12): Result_12 {
    return from_candid_variant_n70(value);
}
function from_candid_Result_13_n71(value: _Result_13): Result_13 {
    return from_candid_variant_n72(value);
}
function from_candid_Result_14_n74(value: _Result_14): Result_14 {
    return from_candid_variant_n75(value);
}
function from_candid_Result_15_n78(value: _Result_15): Result_15 {
    return from_candid_variant_n79(value);
}
function from_candid_Result_16_n80(value: _Result_16): Result_16 {
    return from_candid_variant_n81(value);
}
function from_candid_Result_17_n82(value: _Result_17): Result_17 {
    return from_candid_variant_n83(value);
}
function from_candid_Result_1_n11(value: _Result_1): Result_1 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_2_n12(value: _Result_2): Result_2 {
    return from_candid_variant_n13(value);
}
function from_candid_Result_3_n14(value: _Result_3): Result_3 {
    return from_candid_variant_n15(value);
}
function from_candid_Result_4_n16(value: _Result_4): Result_4 {
    return from_candid_variant_n17(value);
}
function from_candid_Result_5_n36(value: _Result_5): Result_5 {
    return from_candid_variant_n37(value);
}
function from_candid_Result_6_n38(value: _Result_6): Result_6 {
    return from_candid_variant_n39(value);
}
function from_candid_Result_7_n40(value: _Result_7): Result_7 {
    return from_candid_variant_n41(value);
}
function from_candid_Result_8_n42(value: _Result_8): Result_8 {
    return from_candid_variant_n43(value);
}
function from_candid_Result_9_n48(value: _Result_9): Result_9 {
    return from_candid_variant_n49(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_opt_n34(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(value: {
    requirements: _AttestationRequirements;
}): {
    requirements: AttestationRequirements;
} {
    return {
        requirements: from_candid_AttestationRequirements_n20(value.requirements)
    };
}
function from_candid_record_n21(value: {
    max_attestation_age_ns: bigint;
    min_report_version: number;
    require_ciphertext_hiding_enabled: boolean;
    require_tsme_disabled: boolean;
    genoa_policy: _GenTcbRequirements;
    expected_measurement_len: bigint;
    measurements: Array<_AttestationMeasurement>;
    require_ecc_enabled: boolean;
    require_smt_disabled: boolean;
    turin_policy: _GenTcbRequirements;
    require_rapl_disabled: boolean;
    milan_policy: _GenTcbRequirements;
}): {
    max_attestation_age_ns: bigint;
    min_report_version: number;
    require_ciphertext_hiding_enabled: boolean;
    require_tsme_disabled: boolean;
    genoa_policy: GenTcbRequirements;
    expected_measurement_len: bigint;
    measurements: Array<AttestationMeasurement>;
    require_ecc_enabled: boolean;
    require_smt_disabled: boolean;
    turin_policy: GenTcbRequirements;
    require_rapl_disabled: boolean;
    milan_policy: GenTcbRequirements;
} {
    return {
        max_attestation_age_ns: value.max_attestation_age_ns,
        min_report_version: value.min_report_version,
        require_ciphertext_hiding_enabled: value.require_ciphertext_hiding_enabled,
        require_tsme_disabled: value.require_tsme_disabled,
        genoa_policy: value.genoa_policy,
        expected_measurement_len: value.expected_measurement_len,
        measurements: from_candid_vec_n22(value.measurements),
        require_ecc_enabled: value.require_ecc_enabled,
        require_smt_disabled: value.require_smt_disabled,
        turin_policy: value.turin_policy,
        require_rapl_disabled: value.require_rapl_disabled,
        milan_policy: value.milan_policy
    };
}
function from_candid_record_n24(value: {
    status: _MeasurementStatus;
    updated_at: bigint;
    name: string;
    created_at: bigint;
    measurement_hex: string;
}): {
    status: MeasurementStatus;
    updated_at: bigint;
    name: string;
    created_at: bigint;
    measurement_hex: string;
} {
    return {
        status: from_candid_MeasurementStatus_n25(value.status),
        updated_at: value.updated_at,
        name: value.name,
        created_at: value.created_at,
        measurement_hex: value.measurement_hex
    };
}
function from_candid_record_n28(value: {
    models: Array<_Model>;
}): {
    models: Array<Model>;
} {
    return {
        models: from_candid_vec_n29(value.models)
    };
}
function from_candid_record_n31(value: {
    maker: string;
    status: _ModelStatus;
    max_tools: number;
    max_output: number;
    provider: string;
    release_date: [] | [string];
    extra_body_json: [] | [string];
    max_image_attachments: number;
    name: string;
    description: string;
    output_token_price: number;
    provider_model: string;
    provider_endpoint: string;
    is_featured: boolean;
    input_token_price: number;
    is_reasoning: boolean;
    model_id: string;
    aa_score: [] | [number];
    is_embedding: boolean;
    max_context: number;
}): {
    maker: string;
    status: ModelStatus;
    max_tools: number;
    max_output: number;
    provider: string;
    release_date?: string;
    extra_body_json?: string;
    max_image_attachments: number;
    name: string;
    description: string;
    output_token_price: number;
    provider_model: string;
    provider_endpoint: string;
    is_featured: boolean;
    input_token_price: number;
    is_reasoning: boolean;
    model_id: string;
    aa_score?: number;
    is_embedding: boolean;
    max_context: number;
} {
    return {
        maker: value.maker,
        status: from_candid_ModelStatus_n32(value.status),
        max_tools: value.max_tools,
        max_output: value.max_output,
        provider: value.provider,
        release_date: record_opt_to_undefined(from_candid_opt_n34(value.release_date)),
        extra_body_json: record_opt_to_undefined(from_candid_opt_n34(value.extra_body_json)),
        max_image_attachments: value.max_image_attachments,
        name: value.name,
        description: value.description,
        output_token_price: value.output_token_price,
        provider_model: value.provider_model,
        provider_endpoint: value.provider_endpoint,
        is_featured: value.is_featured,
        input_token_price: value.input_token_price,
        is_reasoning: value.is_reasoning,
        model_id: value.model_id,
        aa_score: record_opt_to_undefined(from_candid_opt_n35(value.aa_score)),
        is_embedding: value.is_embedding,
        max_context: value.max_context
    };
}
function from_candid_record_n45(value: {
    command: _NodeHeartbeatCommand;
}): {
    command: NodeHeartbeatCommand;
} {
    return {
        command: from_candid_NodeHeartbeatCommand_n46(value.command)
    };
}
function from_candid_record_n53(value: {
    nodes: Array<_PublicNodeInfo>;
}): {
    nodes: Array<PublicNodeInfo>;
} {
    return {
        nodes: from_candid_vec_n54(value.nodes)
    };
}
function from_candid_record_n56(value: {
    node_id: bigint;
    public_key: [] | [string];
    owner: Principal;
    detected_generation: [] | [string];
    hostname: string;
    attestation_verified_at: [] | [bigint];
    reported_measurement_hex: [] | [string];
    is_active: boolean;
    model_id: string;
    reported_chip_id_hex: [] | [string];
    node_principal: [] | [Principal];
    last_heartbeat_timestamp: [] | [bigint];
}): {
    node_id: bigint;
    public_key?: string;
    owner: Principal;
    detected_generation?: string;
    hostname: string;
    attestation_verified_at?: bigint;
    reported_measurement_hex?: string;
    is_active: boolean;
    model_id: string;
    reported_chip_id_hex?: string;
    node_principal?: Principal;
    last_heartbeat_timestamp?: bigint;
} {
    return {
        node_id: value.node_id,
        public_key: record_opt_to_undefined(from_candid_opt_n34(value.public_key)),
        owner: value.owner,
        detected_generation: record_opt_to_undefined(from_candid_opt_n34(value.detected_generation)),
        hostname: value.hostname,
        attestation_verified_at: record_opt_to_undefined(from_candid_opt_n57(value.attestation_verified_at)),
        reported_measurement_hex: record_opt_to_undefined(from_candid_opt_n34(value.reported_measurement_hex)),
        is_active: value.is_active,
        model_id: value.model_id,
        reported_chip_id_hex: record_opt_to_undefined(from_candid_opt_n34(value.reported_chip_id_hex)),
        node_principal: record_opt_to_undefined(from_candid_opt_n58(value.node_principal)),
        last_heartbeat_timestamp: record_opt_to_undefined(from_candid_opt_n57(value.last_heartbeat_timestamp))
    };
}
function from_candid_record_n62(value: {
    assigned: Array<_CanisterPoolEntry>;
    available: Array<_CanisterPoolEntry>;
    pool_target_size: number;
}): {
    assigned: Array<CanisterPoolEntry>;
    available: Array<CanisterPoolEntry>;
    pool_target_size: number;
} {
    return {
        assigned: from_candid_vec_n63(value.assigned),
        available: from_candid_vec_n63(value.available),
        pool_target_size: value.pool_target_size
    };
}
function from_candid_record_n65(value: {
    time_created: bigint;
    canister_id: Principal;
    state: _CanisterPoolState;
}): {
    time_created: bigint;
    canister_id: Principal;
    state: CanisterPoolState;
} {
    return {
        time_created: value.time_created,
        canister_id: value.canister_id,
        state: from_candid_CanisterPoolState_n66(value.state)
    };
}
function from_candid_record_n68(value: {
    owner: Principal;
    expires_at: [] | [bigint];
}): {
    owner: Principal;
    expires_at?: bigint;
} {
    return {
        owner: value.owner,
        expires_at: record_opt_to_undefined(from_candid_opt_n57(value.expires_at))
    };
}
function from_candid_record_n77(value: {
    canisters: Array<_CanisterPoolEntry>;
}): {
    canisters: Array<CanisterPoolEntry>;
} {
    return {
        canisters: from_candid_vec_n63(value.canisters)
    };
}
function from_candid_variant_n13(value: {
    Ok: _CreateIndexNodeResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: CreateIndexNodeResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n15(value: {
    Ok: _CreateUserCanisterResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: CreateUserCanisterResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n17(value: {
    Ok: _GetAttestationRequirementsResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: GetAttestationRequirementsResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_GetAttestationRequirementsResponse_n18(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: null;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n26(value: {
    Active: null;
} | {
    Deprecated: null;
} | {
    Revoked: null;
}): MeasurementStatus {
    return "Active" in value ? MeasurementStatus.Active : "Deprecated" in value ? MeasurementStatus.Deprecated : "Revoked" in value ? MeasurementStatus.Revoked : value;
}
function from_candid_variant_n33(value: {
    Paused: null;
} | {
    Active: null;
}): ModelStatus {
    return "Paused" in value ? ModelStatus.Paused : "Active" in value ? ModelStatus.Active : value;
}
function from_candid_variant_n37(value: {
    Ok: _GetNodeConfigResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: GetNodeConfigResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n39(value: {
    Ok: _GetProvisioningInfoResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: GetProvisioningInfoResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n4(value: {
    CannotDeleteRootFolder: null;
} | {
    UserAlreadyRegistered: null;
} | {
    InvalidFileName: string;
} | {
    DeleteNonEmptyFolder: null;
} | {
    ModelNotFound: null;
} | {
    InvalidPathDepth: null;
} | {
    InvalidInput: string;
} | {
    UnsupportedMimeType: string;
} | {
    PoolExhausted: null;
} | {
    NoAvailableUserCanister: null;
} | {
    MessageNotFound: null;
} | {
    FileSystemLimitExceeded: string;
} | {
    ChatNotFound: null;
} | {
    Unauthorized: null;
} | {
    FileNotFound: null;
} | {
    CallError: string;
} | {
    PathNotFound: null;
} | {
    ItemNameCollision: string;
} | {
    GenerationInProgress: null;
} | {
    NodeNotFound: null;
} | {
    InvalidSecretKey: null;
} | {
    FolderNotFound: null;
} | {
    Other: string;
} | {
    TrialExpired: null;
} | {
    RoleAlreadyClaimed: null;
} | {
    UserNotFound: null;
}): {
    __kind__: "CannotDeleteRootFolder";
    CannotDeleteRootFolder: null;
} | {
    __kind__: "UserAlreadyRegistered";
    UserAlreadyRegistered: null;
} | {
    __kind__: "InvalidFileName";
    InvalidFileName: string;
} | {
    __kind__: "DeleteNonEmptyFolder";
    DeleteNonEmptyFolder: null;
} | {
    __kind__: "ModelNotFound";
    ModelNotFound: null;
} | {
    __kind__: "InvalidPathDepth";
    InvalidPathDepth: null;
} | {
    __kind__: "InvalidInput";
    InvalidInput: string;
} | {
    __kind__: "UnsupportedMimeType";
    UnsupportedMimeType: string;
} | {
    __kind__: "PoolExhausted";
    PoolExhausted: null;
} | {
    __kind__: "NoAvailableUserCanister";
    NoAvailableUserCanister: null;
} | {
    __kind__: "MessageNotFound";
    MessageNotFound: null;
} | {
    __kind__: "FileSystemLimitExceeded";
    FileSystemLimitExceeded: string;
} | {
    __kind__: "ChatNotFound";
    ChatNotFound: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "FileNotFound";
    FileNotFound: null;
} | {
    __kind__: "CallError";
    CallError: string;
} | {
    __kind__: "PathNotFound";
    PathNotFound: null;
} | {
    __kind__: "ItemNameCollision";
    ItemNameCollision: string;
} | {
    __kind__: "GenerationInProgress";
    GenerationInProgress: null;
} | {
    __kind__: "NodeNotFound";
    NodeNotFound: null;
} | {
    __kind__: "InvalidSecretKey";
    InvalidSecretKey: null;
} | {
    __kind__: "FolderNotFound";
    FolderNotFound: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "TrialExpired";
    TrialExpired: null;
} | {
    __kind__: "RoleAlreadyClaimed";
    RoleAlreadyClaimed: null;
} | {
    __kind__: "UserNotFound";
    UserNotFound: null;
} {
    return "CannotDeleteRootFolder" in value ? {
        __kind__: "CannotDeleteRootFolder",
        CannotDeleteRootFolder: value.CannotDeleteRootFolder
    } : "UserAlreadyRegistered" in value ? {
        __kind__: "UserAlreadyRegistered",
        UserAlreadyRegistered: value.UserAlreadyRegistered
    } : "InvalidFileName" in value ? {
        __kind__: "InvalidFileName",
        InvalidFileName: value.InvalidFileName
    } : "DeleteNonEmptyFolder" in value ? {
        __kind__: "DeleteNonEmptyFolder",
        DeleteNonEmptyFolder: value.DeleteNonEmptyFolder
    } : "ModelNotFound" in value ? {
        __kind__: "ModelNotFound",
        ModelNotFound: value.ModelNotFound
    } : "InvalidPathDepth" in value ? {
        __kind__: "InvalidPathDepth",
        InvalidPathDepth: value.InvalidPathDepth
    } : "InvalidInput" in value ? {
        __kind__: "InvalidInput",
        InvalidInput: value.InvalidInput
    } : "UnsupportedMimeType" in value ? {
        __kind__: "UnsupportedMimeType",
        UnsupportedMimeType: value.UnsupportedMimeType
    } : "PoolExhausted" in value ? {
        __kind__: "PoolExhausted",
        PoolExhausted: value.PoolExhausted
    } : "NoAvailableUserCanister" in value ? {
        __kind__: "NoAvailableUserCanister",
        NoAvailableUserCanister: value.NoAvailableUserCanister
    } : "MessageNotFound" in value ? {
        __kind__: "MessageNotFound",
        MessageNotFound: value.MessageNotFound
    } : "FileSystemLimitExceeded" in value ? {
        __kind__: "FileSystemLimitExceeded",
        FileSystemLimitExceeded: value.FileSystemLimitExceeded
    } : "ChatNotFound" in value ? {
        __kind__: "ChatNotFound",
        ChatNotFound: value.ChatNotFound
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "FileNotFound" in value ? {
        __kind__: "FileNotFound",
        FileNotFound: value.FileNotFound
    } : "CallError" in value ? {
        __kind__: "CallError",
        CallError: value.CallError
    } : "PathNotFound" in value ? {
        __kind__: "PathNotFound",
        PathNotFound: value.PathNotFound
    } : "ItemNameCollision" in value ? {
        __kind__: "ItemNameCollision",
        ItemNameCollision: value.ItemNameCollision
    } : "GenerationInProgress" in value ? {
        __kind__: "GenerationInProgress",
        GenerationInProgress: value.GenerationInProgress
    } : "NodeNotFound" in value ? {
        __kind__: "NodeNotFound",
        NodeNotFound: value.NodeNotFound
    } : "InvalidSecretKey" in value ? {
        __kind__: "InvalidSecretKey",
        InvalidSecretKey: value.InvalidSecretKey
    } : "FolderNotFound" in value ? {
        __kind__: "FolderNotFound",
        FolderNotFound: value.FolderNotFound
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "TrialExpired" in value ? {
        __kind__: "TrialExpired",
        TrialExpired: value.TrialExpired
    } : "RoleAlreadyClaimed" in value ? {
        __kind__: "RoleAlreadyClaimed",
        RoleAlreadyClaimed: value.RoleAlreadyClaimed
    } : "UserNotFound" in value ? {
        __kind__: "UserNotFound",
        UserNotFound: value.UserNotFound
    } : value;
}
function from_candid_variant_n41(value: {
    Ok: _GetUserAssignmentResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: GetUserAssignmentResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n43(value: {
    Ok: _HeartbeatResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: HeartbeatResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_HeartbeatResponse_n44(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n47(value: {
    Continue: null;
} | {
    Abort: null;
} | {
    DrainAndShutdown: null;
}): NodeHeartbeatCommand {
    return "Continue" in value ? NodeHeartbeatCommand.Continue : "Abort" in value ? NodeHeartbeatCommand.Abort : "DrainAndShutdown" in value ? NodeHeartbeatCommand.DrainAndShutdown : value;
}
function from_candid_variant_n49(value: {
    Ok: _IsManagerResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: IsManagerResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n51(value: {
    Ok: _ListActiveNodesResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ListActiveNodesResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ListActiveNodesResponse_n52(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n60(value: {
    Ok: _ListCanisterPoolResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ListCanisterPoolResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ListCanisterPoolResponse_n61(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n67(value: {
    Available: null;
} | {
    Assigned: {
        owner: Principal;
        expires_at: [] | [bigint];
    };
}): {
    __kind__: "Available";
    Available: null;
} | {
    __kind__: "Assigned";
    Assigned: {
        owner: Principal;
        expires_at?: bigint;
    };
} {
    return "Available" in value ? {
        __kind__: "Available",
        Available: value.Available
    } : "Assigned" in value ? {
        __kind__: "Assigned",
        Assigned: from_candid_record_n68(value.Assigned)
    } : value;
}
function from_candid_variant_n70(value: {
    Ok: _ListManagersResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ListManagersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n72(value: {
    Ok: _ListMyNodesResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ListMyNodesResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ListMyNodesResponse_n73(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n75(value: {
    Ok: _ListUserCanistersResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ListUserCanistersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ListUserCanistersResponse_n76(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n79(value: {
    Ok: _ProvisionCanistersResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: ProvisionCanistersResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n81(value: {
    Ok: _RegisterNodeResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: RegisterNodeResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_variant_n83(value: {
    Ok: _RegisterUserResponse;
} | {
    Err: _CanisterError;
}): {
    __kind__: "Ok";
    Ok: RegisterUserResponse;
} | {
    __kind__: "Err";
    Err: CanisterError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_CanisterError_n3(value.Err)
    } : value;
}
function from_candid_vec_n22(value: Array<_AttestationMeasurement>): Array<AttestationMeasurement> {
    return value.map((x)=>from_candid_AttestationMeasurement_n23(x));
}
function from_candid_vec_n29(value: Array<_Model>): Array<Model> {
    return value.map((x)=>from_candid_Model_n30(x));
}
function from_candid_vec_n54(value: Array<_PublicNodeInfo>): Array<PublicNodeInfo> {
    return value.map((x)=>from_candid_PublicNodeInfo_n55(x));
}
function from_candid_vec_n63(value: Array<_CanisterPoolEntry>): Array<CanisterPoolEntry> {
    return value.map((x)=>from_candid_CanisterPoolEntry_n64(x));
}
function to_candid_AddModelRequest_n5(value: AddModelRequest): _AddModelRequest {
    return to_candid_record_n6(value);
}
function to_candid_MeasurementStatus_n86(value: MeasurementStatus): _MeasurementStatus {
    return to_candid_variant_n87(value);
}
function to_candid_ModelStatus_n9(value: ModelStatus): _ModelStatus {
    return to_candid_variant_n10(value);
}
function to_candid_Model_n7(value: Model): _Model {
    return to_candid_record_n8(value);
}
function to_candid_UpdateMeasurementStatusRequest_n84(value: UpdateMeasurementStatusRequest): _UpdateMeasurementStatusRequest {
    return to_candid_record_n85(value);
}
function to_candid_record_n6(value: {
    model: Model;
}): {
    model: _Model;
} {
    return {
        model: to_candid_Model_n7(value.model)
    };
}
function to_candid_record_n8(value: {
    maker: string;
    status: ModelStatus;
    max_tools: number;
    max_output: number;
    provider: string;
    release_date?: string;
    extra_body_json?: string;
    max_image_attachments: number;
    name: string;
    description: string;
    output_token_price: number;
    provider_model: string;
    provider_endpoint: string;
    is_featured: boolean;
    input_token_price: number;
    is_reasoning: boolean;
    model_id: string;
    aa_score?: number;
    is_embedding: boolean;
    max_context: number;
}): {
    maker: string;
    status: _ModelStatus;
    max_tools: number;
    max_output: number;
    provider: string;
    release_date: [] | [string];
    extra_body_json: [] | [string];
    max_image_attachments: number;
    name: string;
    description: string;
    output_token_price: number;
    provider_model: string;
    provider_endpoint: string;
    is_featured: boolean;
    input_token_price: number;
    is_reasoning: boolean;
    model_id: string;
    aa_score: [] | [number];
    is_embedding: boolean;
    max_context: number;
} {
    return {
        maker: value.maker,
        status: to_candid_ModelStatus_n9(value.status),
        max_tools: value.max_tools,
        max_output: value.max_output,
        provider: value.provider,
        release_date: value.release_date ? candid_some(value.release_date) : candid_none(),
        extra_body_json: value.extra_body_json ? candid_some(value.extra_body_json) : candid_none(),
        max_image_attachments: value.max_image_attachments,
        name: value.name,
        description: value.description,
        output_token_price: value.output_token_price,
        provider_model: value.provider_model,
        provider_endpoint: value.provider_endpoint,
        is_featured: value.is_featured,
        input_token_price: value.input_token_price,
        is_reasoning: value.is_reasoning,
        model_id: value.model_id,
        aa_score: value.aa_score ? candid_some(value.aa_score) : candid_none(),
        is_embedding: value.is_embedding,
        max_context: value.max_context
    };
}
function to_candid_record_n85(value: {
    status: MeasurementStatus;
    measurement_hex: string;
}): {
    status: _MeasurementStatus;
    measurement_hex: string;
} {
    return {
        status: to_candid_MeasurementStatus_n86(value.status),
        measurement_hex: value.measurement_hex
    };
}
function to_candid_variant_n10(value: ModelStatus): {
    Paused: null;
} | {
    Active: null;
} {
    return value == ModelStatus.Paused ? {
        Paused: null
    } : value == ModelStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n87(value: MeasurementStatus): {
    Active: null;
} | {
    Deprecated: null;
} | {
    Revoked: null;
} {
    return value == MeasurementStatus.Active ? {
        Active: null
    } : value == MeasurementStatus.Deprecated ? {
        Deprecated: null
    } : value == MeasurementStatus.Revoked ? {
        Revoked: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Gpt_index {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Gpt_index(actor);
}
